### PR TITLE
Added injfilterrejector for multi ifo. 

### PR DESCRIPTION
**Pull request by idorrington92**
This just added the options for the multi ifo version, and makes a dictionary from running the old injfilterrejector on each ifo.

### CODE REVIEW

**Comment by spxiwh** [comment]
@idorrington92 See the CodeClimate report, some of this is formatting, but there's genuine bugs in there too.

Beyond that, this probably would need to be hooked into `pycbc_multi_inspiral` before testing. I'm happy to merge this (once CodeClimate issues are fixed) and then merge that separately.

**Comment by idorrington92** [comment]
Hi Ian,
I'm on holiday for a couple of weeks, I'll look into this when I get a
moment. If it's significant changes I'll do it when I get back to work.

Thanks,
Iain

**Comment by spxiwh** [comment]
Hi @idorrington92. No worries, I don't think this is too major, but ignore this until you're back from vacation!

**Comment by idorrington92** [comment]
I've fixed the codeclimate issues. I  think this can be merged now. Thanks

**Pull request merged**
