### PR TITLE
Allow injection set to write string datatypes

### PR DESCRIPTION
**Pull request by cdcapano**
Fixes Issue #3427 

As described in there , `InjectionSet.write` fails if any of the injection parameters are strings. This can happen when writing an injection set that was loaded from another injection file. The reason is when the injections are loaded, any static arguments are expanded to fields. This is done using `numpy.repeat`. By default, numpy will store the python3 `str` as `U` type, but `h5py` doesn't know how to write that: if try to write the table back out, you'll get a `TypeError`. For example, say I have an injection file that has `approximant = IMRPhenomD` (as is the case in the example given in #3427). Since this is a static argument, it is stored in the injection file's `.attrs` as a `str`:
```
>>> injs = InjectionSet('injections.hdf')
>>> injs._injhandler.filehandler.attrs['approximant']
'IMRPhenomD'
>>> type(injs._injhandler.filehandler.attrs['approximant'])
str
```
The `InjectionSet`'s `.table` will therefore have an `approximant` field which is:
```
>>> injs.table['approximant']
array(['IMRPhenomD', 'IMRPhenomD', 'IMRPhenomD', 'IMRPhenomD',
       'IMRPhenomD'], dtype='<U10')
```
If you then try to do:
```
InjectionSet.write('test.hdf', injs.table)
```
You'll get a `TypeError`.

This fixes this by converting any arrays with `U` type to `S` types before writing. Since this means reading an injection file with strings will return byte arrays, I've also made it so that the read function converts all 'S' type arrays to 'U' type when loading. (If you don't do this, you'll get a byte type when you pull out the approximant, which will cause errors elsewhere.)

### CODE REVIEW

**Comment by ahnitz** [comment]
@cdcapano Thanks for fixing this! I was worried it might be more complicated.

**Comment by titodalcanton** [comment]
Thanks @cdcapano. I quickly tried this on my test code described in #3427, and it seems to work as long as I generate the original HDF injection file *after* your patch. If, instead, I try to read and rewrite an old HDF file, I get this error:
```
Traceback (most recent call last):
  File "test_injection_io.py", line 3, in <module>
    injs = InjectionSet('injections.hdf')
  File "/home/tito/virtualenvs/pycbc_dev_py3/lib/python3.6/site-packages/pycbc/inject/inject.py", line 801, in __init__
    self._injhandler = get_hdf_injtype(sim_file)(sim_file, **kwds)
  File "/home/tito/virtualenvs/pycbc_dev_py3/lib/python3.6/site-packages/pycbc/inject/inject.py", line 748, in get_hdf_injtype
    return hdfinjtypes[ftype]
KeyError: b'cbc'
```
So I think this PR fixes the issue, but it will break reading old HDF files. If this is not a problem, I can approve this.

**Comment by cdcapano** [comment]
@titodalcanton I think that's a bug separate from this. Was the file you tested on created in python 2? I can try to add a fix for that in this patch too.

**Review by titodalcanton — APPROVED** [review]
You are right, I only get that error if the initial file is generated on Python 2. So I am approving this, and feel free to keep that for a new PR.

**Pull request merged**
