### PR TITLE
changed name of multi p astro file

### PR DESCRIPTION
**Pull request by tdent**
Seems simple.

### CODE REVIEW

**Comment by titodalcanton** [comment]
The requirement document seems to indicate `pycbc.p_astro.json` though, with a period.

**Comment by titodalcanton** [comment]
This change also seems problematic because all candidates will now create a file with the same name, overwriting the p_astro file from previous candidates.

**Comment by tdent** [comment]
> This change also seems problematic because all candidates will now create a file with the same name, overwriting the p_astro file from previous candidates.

I know, this is a generic issue with the pycbc model of 'save all files locally and also upload them to gracedb' - if the main method for storing information is considered to be the gracedb event then what we do with files in the pycbc live account is not important.

Any concrete suggestion?

**Comment by titodalcanton** [comment]
> …what we do with files in the pycbc live account is not important.

In my view, it is essential that we keep copies of the candidate files on a permanent and independent storage, since we do not control what really happens with GraceDB. Uploads can fail, and candidates uploaded to gracedb-playground are periodically deleted.

For a concerete suggestion, this would be solved by #4197.

**Comment by tdent** [comment]
> > …what we do with files in the pycbc live account is not important.
> 
> In my view, it is essential that we keep copies of the candidate files on a permanent and independent storage, since we do not control what really happens with GraceDB. Uploads can fail, and candidates uploaded to gracedb-playground are periodically deleted.
> 
> For a concerete suggestion, this would be solved by #4197.

the first part of the quote says, _if_ we consider gracedb as the main storage, which might be what other pipelines are doing, and I'm guessing is what other bits of the collaboration are expecting, but is not necessarily what we want.

**Comment by titodalcanton** [comment]
In my opinion we put this on hold until #4197 (or equivalent) is addressed.

**Comment by titodalcanton** [comment]
We also need the `p_astro` tag on the file, by the way.

**Comment by tdent** [comment]
@titodalcanton any changes needed here?

**Comment by titodalcanton** [comment]
Probably just a rebase on master.

**Comment by titodalcanton** [comment]
Sorry, you also need to make sure the file ends up in the right directory for the candidate. Use `os.path.basename()` to figure out the path to the directory containing the XML file, then use `os.path.join()` to combine the directory path with the new file name.

**Comment by tdent** [comment]
> Use os.path.basename() to figure out the path to the directory containing the XML file, then use os.path.join() to combine the directory path with the new file name.

I think you mean os.path.dirname() ?

**Comment by tdent** [comment]
Changes here are being rolled into #4205, closing

**Pull request closed without merging**
