### PR TITLE
add foreground ifar plot for multi-ifo pipeline

### PR DESCRIPTION
**Pull request by tdent**

### CODE REVIEW

**Comment by ahnitz** [comment]
@tdent I don't have any major questions about this. Only to note that it might be useful for this to be able to support taking in multiple trigger files.

**Comment by tdent** [comment]
multiple trigger files meaning for analyses of different disjoint periods of time which should be combined in the plot?  (overlapping times would be harder ..)

**Comment by ahnitz** [comment]
@tdent yes, for disjoint times

**Comment by tdent** [comment]
if you feel like testing this out on >1 statmap fill go ahead .. so far it's just my guesses at what ought to work

**Pull request merged**
