### PR TITLE
Merge the inference dev branch on to master

### PR DESCRIPTION
**Pull request by cdcapano**
Final PR to merge the inference dev branch on to master. The commits here should not be squashed, to keep the contributions from everyone intact.

### CODE REVIEW

**Comment by spxiwh** [comment]
Please rebase the branch to recent master to fix the codeclimate issues.

**Comment by cdcapano** [comment]
Thanks @spxiwh; I've rebased to master (and also fixed the merge conflict).

**Comment by cdcapano** [comment]
@duncan-brown I'd like to get it merged as soon as I can fix all of the codebeat and codeclimate issues (if they'll ever show me what's going on). Also Travis, but that looks to be unrelated.

**Comment by cdcapano** [comment]
@duncan-brown Ok, travis is passing again for this. I'd like to merge this tomorrow morning. Can a release be created by then?

**Pull request merged**
