### PR TITLE
allow pycbc live to accept multiple triggers each chunk from each template

### PR DESCRIPTION
**Pull request by ahnitz**

### CODE REVIEW

**Comment by titodalcanton** [comment]
I finally get back to this. @ahnitz can you remind me what was the goal here? Is the idea to prevent loud glitches from killing all triggers? Also, can you rebase it on master so it is easier to test?

**Comment by spxiwh** [comment]
@titodalcanton Yeah this was based around discussion of one loud glitch being able to suppress triggers in a large region around it. Being able to accept multiple triggers from each template would help to alleviate this (as would accepting more than N triggers across all templates per chunk, or at least if keeping only N triggers, it would be nice to have triggers at multiple times, and not all at the time of the glitch).

**Comment by ahnitz** [comment]
@spxiwh Exactly. This was the first step to helping with that. This will increase the trigger rate proportionately (and so increase the background cost as well). The idea though was to not throw away these triggers too early, and it might be possible to add a simple heuristic to detect glitch and not vacuum up all the single-detector triggers down the line if additional clustering is needed beyond this point to keep the trigger rate in check.

**Comment by ahnitz** [comment]
@titodalcanton This has been rebased and I think the cc should be ok now.

**Pull request merged**
