### PR TITLE
Cherry-picked commits for 2.1.3 release

### PR DESCRIPTION
**Pull request by titodalcanton**

### CODE REVIEW

**Comment by titodalcanton** [comment]
Make sure to use “Rebase and merge”, not the default “Squash and merge”, so that history is preserved for reviewers.

**Comment by spxiwh** [comment]
As well as #4580, I would take the last 5 patches from https://github.com/spxiwh/pycbc/commits/v233_release_branch/ This reverts #4289 and then does some cleanup related to it.

**Comment by maxtrevor** [comment]
Where do we stand on this after today's call? It sounded like we will want a new release branch, so do we still need to do the 2.1.3 release?

**Comment by titodalcanton** [comment]
@maxtrevor I will poke at this a bit more to see if I can make the tests pass, but if that takes too long, I might just decide to start a new release line from master.

**Comment by titodalcanton** [comment]
I accidentally pushed to the upstream branch here. The only remaining failures were on the docs though, which we do not care about for this release line, so I suppose this is ok.

**Pull request merged**
