### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by ahnitz**

### CODE REVIEW

**Review by tdent — APPROVED** [review]

**Comment by titodalcanton** [comment]
Does anyone remember why this was done? Can it be reverted now?

**Comment by ahnitz** [comment]
@titodalcanton I think it's a compatibility issue with emcee. We may need to update some examples. Can you open a revert PR anyway? We should get that working, but we'll need to add a few docs changes at least I think to get it working.

**Comment by tdent** [comment]
To get round `numpy.float` suddenly disappearing as an available type, I think. 

The plan was to 'fix this properly after the holidays' (meaning in January 2023).

**Comment by ahnitz** [comment]
@tdent Yeah, which clearly I didn't do. No so surprising since that's around my job change time. I completely forgot about this.

**Comment by titodalcanton** [comment]
It is technically "after the holidays" now, so… Here we are.

**Pull request merged**
