### PR TITLE
Offline singles in workflow

### PR DESCRIPTION
**Pull request by GarethCabournDavies**
Alter the workflow to analyze single-detector candidates given a specific flag, and rename `pycbc_make_coinc_search_workflow` to `pycbc_make_offline_search_workflow` in order to reflect this change

Specific flag is that there is the section `[workflow-singles]` with the option `analyze` set.

Note: as this has changed the name of the workflow generator, stored offline workflow config files will need updated

Draft status is in order to get testing to complete

### CODE REVIEW

**Comment by GarethCabournDavies** [comment]
Not sure how best to fix the codeclimate complaints here

**Review by spxiwh — APPROVED** [review]
I'm happy with this, and you can ignore the remaining CC requests.

Most important here is that it's tested in the expected use cases and does what we expect.

**Comment by GarethCabournDavies** [comment]
Looking at the results artefact from the CI run, I think I missed off the exclude_zerolag for the single-detector things

**Comment by GarethCabournDavies** [comment]
> Looking at the results artefact from the CI run, I think I missed off the exclude_zerolag for the single-detector things

I found the issue and it is an unrelated bug. @spxiwh - is this still considered approved? Ive added a bit more since the last review (basically to make sure that it does what we want)

**Comment by spxiwh** [comment]
I'm still happy as long as you've tested that this does what we want.

**Pull request merged**
