### PR TITLE
Update get.sh

### PR DESCRIPTION
**Pull request by WuShichao**

### CODE REVIEW

**Comment by titodalcanton** [comment]
@WuShichao please also add the `--show-error` option to the `curl` calls in that script, so `curl` actually prints something when the download fails.

**Comment by WuShichao** [comment]
@titodalcanton Thanks. Let me add this too.

**Comment by titodalcanton** [comment]
…however do please keep the `--silent` option, otherwise `curl` will needlessly spam the log :)

**Comment by titodalcanton** [comment]
Final request, could you do the same fix to the other `get.sh` scripts in the `examples/inference/` directories? At least those which run as part of the test suite. It looks like they have the same problem.

**Pull request merged**
