### PR TITLE
Coherent mfilter

### PR DESCRIPTION
**Pull request by idorrington92**
Development of coherent analysis

### CODE REVIEW

**Comment by spxiwh** [comment]
Check over the codeclimate stuff

**Comment by idorrington92** [comment]
Oh, Almost all of that is some old code I was working on when I first
started. That should really be removed from the repository. I'll do that.

**Comment by spxiwh** [comment]
It's also worth rebasing this against origin/master (this can be explained in Slack if you want to talk with me/Alex/Tom) ... Much of our code checking stuff has been tweaked a bit, but I think this isn't picked up on this branch.

**Comment by ahnitz** [comment]
@idorrington92 @spxiwh Is this deprecated by the #2476 ?

**Comment by spxiwh** [comment]
Closing in favour of #2476

**Pull request closed without merging**
