### PR TITLE
attempting pycbc_astro workflow

### PR DESCRIPTION
**Pull request by vaibhavtewari**
Hi @ahnitz @tdent I am attempting to include pycbc_astro in workflow. Considering I am working with limited understanding this will change significantly. Please advice how to improve on this ?

### CODE REVIEW

**Comment by vaibhavtewari** [comment]
The background information is in,
https://github.com/vaibhavtewari/pycbc/blob/master/pycbc/workflow/scratch_will_delete.txt

**Comment by spxiwh** [comment]
Is this still active?

**Comment by vaibhavtewari** [comment]
Hi @spxiwh let it stay around. This will certainly see light of the day soon enough!

**Comment by spxiwh** [comment]
I'm going to close this now as it's been inactive for quite some time. It's easy to reopen pull requests if needed.

**Pull request closed without merging**
