### PR TITLE
Restrict SSE 4.2 flag to x86_64

### PR DESCRIPTION
**Pull request by titodalcanton**
An attempt at fixing #2927. Not tested; comments welcome.

### CODE REVIEW

**Comment by steffen-AEI** [comment]
> `pip install pycbc` would not include this, but you should be able to manually clone PyCBC from my fork, checkout this branch, and `pip install .`. Otherwise, I will probably get to trying it out tomorrow.

I still must be missing something.
```
root@beeblebrox:~/pycbc# git clone https://github.com/titodalcanton/pycbc.git
Cloning into 'pycbc'...
remote: Enumerating objects: 45054, done.
remote: Total 45054 (delta 0), reused 0 (delta 0), pack-reused 45054
Receiving objects: 100% (45054/45054), 39.15 MiB | 8.97 MiB/s, done.
Resolving deltas: 100% (33528/33528), done.
root@beeblebrox:~/pycbc# cd pycbc/
root@beeblebrox:~/pycbc/pycbc# pip -V
pip 19.2.3 from /usr/local/lib/python3.5/dist-packages/pip-19.2.3-py3.5.egg/pip (python 3.5)
root@beeblebrox:~/pycbc/pycbc# pip install --upgrade pip
Requirement already up-to-date: pip in /usr/local/lib/python3.5/dist-packages/pip-19.2.3-py3.5.egg (19.2.3)
root@beeblebrox:~/pycbc/pycbc# pip install --upgrade setuptools
Requirement already up-to-date: setuptools in /usr/local/lib/python3.5/dist-packages (41.2.0)
root@beeblebrox:~/pycbc/pycbc# pip install .
Processing /root/pycbc/pycbc
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-fs_ebhtg/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-fs_ebhtg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-fs_ebhtg/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-fs_ebhtg/setup.py", line 107
        print 'removed {0}'.format(f)
                          ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I'm about to call it a week now. Take your time...

**Comment by titodalcanton** [comment]
@steffen-AEI after cloning my fork, you should checkout this branch:
```
git clone https://github.com/titodalcanton/pycbc.git
cd pycbc
git checkout enable_non_x86
pip install .
```
otherwise you will be installing my fork's master branch, which may be in some very old non-functional state.

**Comment by titodalcanton** [comment]
FWIW, I just verified that this at least does not break anything on x86.

**Comment by steffen-AEI** [comment]
On Thu, 2019-09-19 at 11:13:17 +0200, Tito Dal Canton wrote:
> Hi Steffen,
> 
> In order to test https://github.com/gwastro/pycbc/pull/2936 I am trying
> to log into the POWER9 machine as you instructed me, but ssh'ing to
> login.megware.com wants me to enter a password for sgrunewald. Does that

I restored your access, but ... see below.

> mean the machine is already gone? If so, do you have another non-x86
> machine I can log into for a moment? If not, I could bring in my
> Raspberry Pi and connect it to the AEI LAN, I guess.

I've got an ARM64 server which is acting as Condor master - so this machine
usually is invisible.

> git clone https://github.com/titodalcanton/pycbc.git
> cd pycbc
> git checkout enable_non_x86
> pip install .

breaks at matplotlib if there are missing lib*-dev packages (png, jpeg, freetype)
- those should be listed somewhere.
I've restarted the build on ARM, but since I'm not root on the POWER machine
that might become a dead end. There's still that VM instance in Brazil I've
got access to (including root privileges), I might try that too.


- S

-- 
Steffen Grunewald, Cluster Administrator
Max Planck Institute for Gravitational Physics (Albert Einstein Institute)
Am Mühlenberg 1 * D-14476 Potsdam-Golm * Germany
~~~
Fon: +49-331-567 7274
Mail: steffen.grunewald(at)aei.mpg.de
~~~

**Comment by steffen-AEI** [comment]
On Thu, 2019-09-19 at 14:49:42 +0200, Steffen Grunewald wrote:
> I've got an ARM64 server which is acting as Condor master - so this machine
> usually is invisible.
and it's running at a low clock, so it stood no chance against both Power instances.

> > git clone https://github.com/titodalcanton/pycbc.git
> > cd pycbc
> > git checkout enable_non_x86
> > pip install .
> 
> breaks at matplotlib if there are missing lib*-dev packages (png, jpeg, freetype)
> - those should be listed somewhere.

Also pkg-config gets suggested.

> I've restarted the build on ARM, but since I'm not root on the POWER machine
> that might become a dead end. There's still that VM instance in Brazil I've
> got access to (including root privileges), I might try that too.

Seems to work - of course I'm now getting errors like "no module named "lal"
(or "lalsimulation", if I pip install GWlal).

We'll need a system-wide install of LALsuite.

I'll try that approach within a container context next - singularity is fun
to play with (Docker OTOH isn't).

Thanks so far,
 Steffen

**Comment by titodalcanton** [comment]
@steffen-AEI  can you confirm that at least this patch removes the initial error, so I can merge it?

**Comment by steffen-AEI** [comment]
On Thu, 2019-09-19 at 08:25:08 -0700, Tito Dal Canton wrote:
> @steffen-AEI  can you confirm that at least this patch removes the initial error, so I can merge it?

Yes I do ;) Even a container built fine (on arm64) using the alternative branch.

Thanks a bunch, Steffen

**Pull request merged**
