### PR TITLE
Revert #4213, a temporary numpy version pin

### PR DESCRIPTION
**Pull request by titodalcanton**

### CODE REVIEW

**Comment by tdent** [comment]
No objection iff the tests pass.

**Comment by titodalcanton** [comment]
Ok I see, this is now failing because emcee (well, the deprecated parallel tempered sampler in an old version of emcee) used `np.float`, which is no longer supported now. Specifically this is the error:
```
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
```

**Comment by spxiwh** [comment]
Is it possible to hack this? Basically here:

https://github.com/gwastro/pycbc/blob/master/pycbc/inference/sampler/emcee_pt.py#L25

after the emcee_pt import, could we do something like `numpy.float = float` to restore the old behaviour?

**Comment by ahnitz** [comment]
> Is it possible to hack this? Basically here:
> 
> https://github.com/gwastro/pycbc/blob/master/pycbc/inference/sampler/emcee_pt.py#L25
> 
> after the emcee_pt import, could we do something like `numpy.float = float` to restore the old behaviour?

Worth a try, makes sense.

**Comment by titodalcanton** [comment]
Seems to work…

**Review by ahnitz — APPROVED** [review]
The hack is self-contained to the module where it is used, so I think that is sufficient. And the longer term plan is probably to simply drop this completely when / if it is no longer easy to maintain on our end.

**Pull request merged**
