### PR TITLE
support for mode by mode decomposition of NRHybSur3dq8 waveform model

### PR DESCRIPTION
**Pull request by lpathak97**

### CODE REVIEW

**Comment by ahnitz** [comment]
@lpathak97 I think you may have accidentally committed a bunch of temporary files that should be part of the repo. Can you clean that up so just your changes are included in the PR?

**Comment by lpathak97** [comment]
@ahnitz Ohh, sorry. Let me clean it up.

**Comment by lpathak97** [comment]
Let me make a fresh pull request and delete this one.

**Comment by ahnitz** [comment]
@lpathak97 FYI, I suggest making PRs from a branch. If you update the branch, it will be reflected in the PR. Using master does the same, but you may have things on the master branch unrelated to the PR in many cases. By updating a branch, you don't need to close PRs to make changes.

**Pull request closed without merging**
