### PR TITLE
coinc_lim_for_thresh for BBH statistics

### PR DESCRIPTION
**Pull request by GarethDaviesGW**
the mchirp weighting got missed off in the coinc_lim_for_thresh stuff, which means that some background coincs were dismissed when they shouldn't have been

### CODE REVIEW

**Review by tdent — APPROVED** [review]

**Comment by connor-mcisaac** [comment]
I guess this assumes that you have run the "single" method before this to get the right chirp mass, which is definitely the case for the findtrigs code, not sure where else this code is used.

**Comment by GarethDaviesGW** [comment]
> I guess this assumes that you have run the "single" method before this to get the right chirp mass, which is definitely the case for the findtrigs code, not sure where else this code is used.

I had considered trying to make this so that it uses the minimum chirp mass from the bank, using the "assume best case scenario" principle, but think that would have been overcomplicating things

**Comment by connor-mcisaac** [comment]
> > I guess this assumes that you have run the "single" method before this to get the right chirp mass, which is definitely the case for the findtrigs code, not sure where else this code is used.
> 
> I had considered trying to make this so that it uses the minimum chirp mass from the bank, using the "assume best case scenario" principle, but think that would have been overcomplicating things

Since the findtrig code only does 1 template at a time it's fine to use the actually mchirp, and as you say it makes thing a bit simpler.

**Review by connor-mcisaac — APPROVED** [review]

**Comment by GarethDaviesGW** [comment]
This has been tested by comparing coinc_findtrigs output with and without this change to coinc_findtrigs output with the coinc_lim_for_thresh disabled. This fixes the problem

**Pull request merged**
