### PR TITLE
Template bank project : changes in faithsim codes 

### PR DESCRIPTION
**Pull request by MPillas**
Changes in `pycbc_make_faithsim` & `pycbc_faithsim` to use them with python3

### CODE REVIEW

**Review by ahnitz — APPROVED** [review]

**Comment by ahnitz** [comment]
@MPillas Thank you for your contribution!

**Comment by MPillas** [comment]
In the `pycbc_make_faithsim` code, is there a way to know or control the number of xml bank files the` inj.xml` file will be split into ? 

I'm referring to this part of the code : 

```
logging.info("Creating injection file")
inj_str = "lalapps_inspinj " + get_ini_opts(confs, "inspinj") + "--output inj.xml"
os.system(inj_str)

logging.info("Splitting template bank")
subprocess.call(['pycbc_splitbank',
                 '--templates-per-bank', str(templates_per_job),
                 '-t', 'inj.xml',
                 '-o', 'bank/bank'])

num_banks = len(glob.glob("bank/bank*"))
```

**Comment by MPillas** [comment]
Problem in `pycbc_faithsim_collect_results` (`part of pycbc_make_faithsim`)

`Traceback (most recent call last):
  File "scripts/pycbc_faithsim_collect_results", line 50, in <module>
    pdata[field] = bt.get_column(field)
AttributeError: 'SimInspiralTable' object has no attribute 'get_column'`

But in the documentation I can clearly see the attribute `get_column` in the `glue.ligolw.lsctables.SimInspiralTable` class. The problem comes from the `mass1` column otherwise it's working.

**Comment by spxiwh** [comment]
Hi Marion. We don't use glue.ligolw any more, we now use ligo.lw. The
syntax there is a little different (not sure offhand what the replacement
is, but I think it would only be a small change).

**Pull request merged**
