### PR TITLE
Added an OSError exception to MKL check in __init__.py

### PR DESCRIPTION
**Pull request by ArthurTolley**
When trying to run the PyCBC Live example I was encountering the error `OSError: libmkl_rt.so.2: cannot open shared object file: No such file or directory`. This was fixed by explicitly running `conda install mkl` in my environment (although I am still getting the same error running the pycbc live o4 production environment).

Copying the error catching found [here](https://github.com/gwastro/pycbc/blob/master/pycbc/fft/core.py#LL53C16-L53C39) (thank you to Ian) to the same check in `__init__.py` clears up this error.

I can provide more information if anyone would like to figure out why this error was happening, especially when using the pycbc live env on CIT.

### CODE REVIEW

**Comment by ArthurTolley** [comment]
A very quick check confirms that this only happens when I run `run.sh` through the VSCode terminal and not on the CIT JupyterHub terminal. The exact same script with the same environment loaded.

**Comment by josh-willis** [comment]
I think we can and should merge this, as it fixes a problem, but I'll note here that there must be either something broken in `libutils.py`, or something inconsistent in the environment where this bug is triggered. The error notes that it can't find `libmkl_rt.so.2`. But the libutil call would not have asked for that, only just `mkl_rt`. So something has at some point decided that there should be a `libmkl_rt.so.2`, but then later when it needs to actually open it, it cannot find it. Which is strange.

**Comment by titodalcanton** [comment]
No particular opinion on this. We do not use MKL for PyCBC Live on CIT anyway, so this would only affect development/testing.

**Comment by spxiwh** [comment]
First up, as Josh says, we should merge this, because we are seeing cases where MKL not being present results in an OSError. The code should default back to FFTW in this case ... Actually that was seen in an env spawned from the PyCBC Live env, so it is perhaps most relevant in the PyCBC Live context where we don't expect MKL. The code to make MKL optional (in pycbc/fft/mkl.py) included this guard, but at a later point the import here was added, and not guarded in the same way.

As Josh says though, it should *not* fail with an OSError, as that indicates that it did find MKL in one call, and then it didn't find MKL in a subsequent call. I think the underlying reason for this is the way conda works on LVK machines. As we saw in the long PR #4394 about failures, I had an environment pulling in libraries that were not in my PATH at all (and indeed weren't even from the same python version, which is concerning!). I think this is the underlying reason why we can "sort of" find MKL, but I don't have a clear reproducible example. I'm not going to be able to dig further into that question at present, but this fix does the obvious problem, especially if PyCBC Live *should* be running with FFTW and not "sort of" finding MKL.

**Comment by titodalcanton** [comment]
I see. So I am going to propose including this in the 2.1.3 release.

**Comment by spxiwh** [comment]
@titodalcanton Yes, please do merge this into the PyCBC Live releases. It won't affect the `pycbc.live` account, I think, but does help people developing from it.

**Pull request merged**
