### PR TITLE
Re-enable failure on Sphinx warnings

### PR DESCRIPTION
**Pull request by titodalcanton**
#3028 removed the `-W` flag to `sphinx-build`, allowing errors in the documentation to go undetected. This reenables the flag and fixes a few errors that would cause Sphinx to fail.

### CODE REVIEW

**Comment by titodalcanton** [comment]
This does not fix all errors, so the doc build fails. The first error is #3880.

**Comment by ahnitz** [comment]
@titodalcanton Try rebasing, #3880 should now be fixed

**Comment by titodalcanton** [comment]
I think I addressed all the easier errors, and this is now held up by errors like these:
```
WARNING: autodoc: failed to import function 'setup_segment_generation' from module 'pycbc.workflow'; the following exception was raised:
Traceback (most recent call last):
  File "…/pycbc/lib/python3.7/site-packages/sphinx/util/inspect.py", line 225, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'pycbc.workflow' has no attribute 'setup_segment_generation'
```
and
```
WARNING: autodoc: failed to import function 'setup_segment_gen_mixed' from module 'pycbc.workflow'; the following exception was raised:
Traceback (most recent call last):
  File "…/pycbc/lib/python3.7/site-packages/sphinx/util/inspect.py", line 225, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'pycbc.workflow' has no attribute 'setup_segment_gen_mixed'
```
@spxiwh do you have any quick **PR**oposal for how to get around those?

**Comment by spxiwh** [comment]
@titodalcanton I just pushed a commit directly onto this branch, which I think should resolve those errors.

**Comment by titodalcanton** [comment]
Looks like `setup_segment_generation` is still referenced in `docs/workflow/datafind.rst`.

**Review by spxiwh — APPROVED** [review]

**Review by ahnitz — APPROVED** [review]

**Pull request merged**
