### PR TITLE
PTA histogram - wrap phase, remove extraneous snr ratio bins

### PR DESCRIPTION
**Pull request by GarethDaviesGW**
Some bins were outside of the ranges of phase difference and SNR ratio due to smoothing

This PR makes the phases wrap back into the 0-2pi range when smoothing and removes any bins above/below the SNR ratio allowed range

### CODE REVIEW

**Comment by tdent** [comment]
is there a plot of the effect of the wrapping / cutting on the phase/time histogram or (say) the snr/time histogram ?

**Comment by GarethDaviesGW** [comment]
>is there a plot of the effect of the wrapping / cutting on the phase/time histogram or (say) the snr/time histogram ?
>(just 2-ifo examples would be fine)

There's a preliminary plot at https://ldas-jobs.ligo-wa.caltech.edu/~gdavies/testoutput/prior_hist_wrap/phasewrapping.png (I'll sort labels and get the plot central in time another day)

**Comment by GarethDaviesGW** [comment]
> is there a plot of the effect of the wrapping / cutting on the phase/time histogram or (say) the snr/time histogram ?
> (just 2-ifo examples would be fine)

H-L plots of the histogram for phase diff vs time diff and snr ratio vs time diff are below:
image

image

**Comment by GarethDaviesGW** [comment]
I think that the weight threshold is different between the two files. I'll see if I can re-run with comparable files

**Comment by GarethDaviesGW** [comment]
With the updated threshold the occupied bins in the allowed region remains the same:
image

image

**Comment by tdent** [comment]
Looks good to me. Which threshold is going to be used in production?

**Comment by GarethDaviesGW** [comment]
The lower threshold (i.e. more bins filled) is the one that has been used in production previously, so I would say to continue with that

**Pull request merged**
