### PR TITLE
Add a Hierarchical model to inference

### PR DESCRIPTION
**Pull request by cdcapano**
Adds a class for hierarchical models. Work in progress.

### CODE REVIEW

**Comment by ahnitz** [comment]
I think the multi signal, shared data model can subclass from this with just an update of the loglikelihood function. I'll try to add that in combination with changes needed to the data models. Out of curiosity can this model contain also another heirachical model? If no, would that be difficult bookkeeping wise?

**Comment by cdcapano** [comment]
Depends on #4029.

**Comment by ahnitz** [comment]
@cdcapano Why have you added a new intermediate class? Is that planning something for the future? If not, it seems like it's adding a shell of complexity for no reason, no?

**Comment by ahnitz** [comment]
@cdcapano I'll defer to you on that one, but thanks for clarifying the problem.

**Review by ahnitz — APPROVED** [review]
Please merge once the tests pass

**Comment by cdcapano** [comment]
@ahnitz I reverted the intermediate class back (option 2 above). I'm just waiting for the `run.sh` to finish on atlas to make sure it completes ok, then I'll merge.

**Comment by ahnitz** [comment]
@cdcapano Did this work out?

**Comment by cdcapano** [comment]
It's still running, but I'm just going to squash and merge since there doesn't appear to be anything wrong. I can add a plot of the results to the doc page in a followup PR.

**Pull request merged**
