### PR TITLE
Remove pycbc_coinc_time

### PR DESCRIPTION
**Pull request by duncanmmacleod**
## Standard information about the request

This is a: other - backwards-incompatible script removal

This change affects: nothing?

This change changes: unknown

This change: has appropriate unit tests, follows style guidelines (See e.g. [PEP8](https://peps.python.org/pep-0008/)), has been proposed using the [contribution guidelines](https://github.com/gwastro/pycbc/blob/master/CONTRIBUTING.md)

This change will: break current functionality, require a new release

## Motivation

The `pycbc_coinc_time` script is the only usage of the `dqsegdb` library in this project. The `dqsegdb` library is dying and doesn't support Python 3.12.

Quoting private communication from @spxiwh: 

> That script is abandonware, it almost certainly needs to be removed from PyCBC

See also #4821.

## Contents

This PR removes the `pycbc_coinc_time` script.

## Additional notes

- [x] The author of this pull request confirms they will adhere to the [code of conduct](https://github.com/gwastro/pycbc/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by GarethCabournDavies** [comment]
This looks good to me, I don't think `pycbc_coinc_time` is used at all either (adding to Ian's point)

Can dqsegdb be removed from requirements-igwn.txt as well then?

**Comment by duncanmmacleod** [comment]
> Can dqsegdb be removed from requirements-igwn.txt as well then?

@GarethCabournDavies (@spxiwh) the only other references to the `dqsegdb` client are in various old workflow `.ini` files, and associated documentation `.rst` files, e.g:

```console
$ git grep _dqsegdb
docs/hwinj.rst:  ligolw_segment_query_dqsegdb --query-segments --segment-url https://dqsegdb5.phy.syr.edu --gps-start-time 1124380361 --gps-end-time 1124382409 --include-segments L1:DMT-ANALYSIS_READY:1 --output-file L1-SEGMENTS.xml
docs/hwinj.rst:  ligolw_segment_query_dqsegdb --query-segments --segment-url https://dqsegdb5.phy.syr.edu --gps-start-time 1124380361 --gps-end-time 1124382409 --include-segments H1:DMT-ANALYSIS_READY:1 --output-file H1-SEGMENTS.xml
docs/resources/er6_bns.ini:segment_query = ${which:ligolw_segment_query_dqsegdb}
docs/resources/er6_bns.ini:segments_from_cats = ${which:ligolw_segments_from_cats_dqsegdb}
<snip>
```

However, I can't see any actual support for `segment_query` and `segments_from_cats` configuration options in the workflow libraries.

So, tentatively, I think that `dqsegdb` ___can___ be removed, but I am not an authority on this.

**Comment by GarethCabournDavies** [comment]
It should be able to be removed. I also checked `git grep "dqsegdb" | grep -v ligolw_segment`

**Comment by duncanmmacleod** [comment]
> Could we just drop the dqsegdb dependency without necessarily removing this script?

@titodalcanton are you suggesting that someone update the script to operate without `dqsegdb`, or leave the script broken in the project?

**Comment by duncanmmacleod** [comment]
> It should be able to be removed. I also checked `git grep "dqsegdb" | grep -v ligolw_segment`

I have updated this PR to remove the requirement.

**Review by GarethCabournDavies — APPROVED** [review]

**Pull request merged**
