### PR TITLE
update github actions

### PR DESCRIPTION
**Pull request by ahnitz**

### CODE REVIEW

**Comment by ahnitz** [comment]
@spxiwh This runs parts of the pycbc test suite in parallel. 

i.e. 

1) help message checks
2) unittests
3) search test scripts
4) inference test scripts
5) documentation build

**Comment by spxiwh** [comment]
@ahnitz If I compare this to other runs, it looks like the total wall time here might be quite a bit longer. Is that right?

**Comment by ahnitz** [comment]
@spxiwh No, it cuts the wall time by just over half. At that point a lot is the initial installation, though the inference could be sped up a bit to get it closer to 10 minutes instead of 15. What are you comparing against? Earlier completed runs were at ~ 36 minutes wall time. Are you comparing to a failed run? I see one of those where all the tests essentially failed immediately and didn't really run which was ~ 9 minutes with your stat.py rework PR.

**Comment by titodalcanton** [comment]
The PyCBC Live test is also quite a bit slower than it should be (I hope to fix that by the end of the year).

**Comment by ahnitz** [comment]
@titodalcanton If needed, we can have tests run on their own. I just did an initial parallelization here that grouped things roughly into similar tasks. It seems like the setup / install is ~ 6 minutes at the moment, so that's a big fraction of the wall time.

**Review by spxiwh — APPROVED** [review]

**Pull request merged**
