### PR TITLE
Add a helper function for log histograms

### PR DESCRIPTION
**Pull request by duncan-brown**
Workaround for issues with matplotlib drawing contours on log plots.

### CODE REVIEW

**Comment by cdcapano** [comment]
@duncan-brown I just noticed this... what was the reason for adding this function? Taking the `log10` of a parameter should already be supported via numpy.

**Comment by duncan-brown** [comment]
@stevereyes01 should confirm, but numpy.log10 is not exposed in a way that the posterior plotting code can use. If it is, then this can be reverted.

**Comment by cdcapano** [comment]
It should be exposed... the way you would do it is `--parameters log10(param)`. @stevereyes01 Did that not work for you? If that's the case, that would be a bug with `FieldArray`...

**Comment by stevereyes01** [comment]
Ah, okay, sorry about that. You're correct. We can revert this. Thanks for that suggestion.

**Comment by duncan-brown** [comment]
@stevereyes01 you probably can't revert this patch, as it will conflict with the changes in https://github.com/gwastro/pycbc/pull/2284 Just submit a new pull request (referencing this one) that removes the function.

**Pull request merged**
