### PR TITLE
Inj finder fix

### PR DESCRIPTION
**Pull request by spxiwh**
#2930 has been open for ages and I think has been lost in Iain moving on to brighter pastures.

As I can't make updates on Iain's branch here is this PR with Duncan's suggestions included. Duncan if you're happy with this please merge, or if I hear nothing I'll close this.

### CODE REVIEW

**Comment by duncan-brown** [comment]
@spxiwh which Duncan?

**Comment by duncan-brown** [comment]
nvm, I see you assigned it to little D.

**Comment by tdent** [comment]
@duncanmmacleod this is assigned to you since December 11 (2 months as of ~today).  Please review it ASAP.

**Comment by duncanmmacleod** [comment]
Sorry for the delay in reviewing this, I tried before but couldn't get my head around the changes. If the code didn't work before this change, but does work after, then it looks ok to me.

**Pull request closed without merging**
