### PR TITLE
try adding a few second timeout

### PR DESCRIPTION
**Pull request by ahnitz**

### CODE REVIEW

**Comment by ahnitz** [comment]
@spxiwh I've put in a different function to download files that allows for automatic retries. That seems to fix most the travis problems. I'm not sure what changed, but for whatever reason a good fraction of the time connection attempts were failing to the gwosc servers to get basically anything, i.e. both dq information but also strain data needed for the tests. 

There is one remaining failure which I've asked @duncan-brown about in the chat. It looks like maybe something has changed so the pegasus executables aren't available to that test environment?

**Comment by spxiwh** [comment]
This is still failing, I think with:

```
/pycbc/tools/test_coinc_search_workflow.sh: line 36: pycbc_make_coinc_search_workflow: command not found
```

which doesn't make a lot of sense to me!

**Comment by ahnitz** [comment]
@spxiwh I have no idea on this one. The error is unrelated to any change I made I think. I don't know what is going wrong there.

**Comment by ahnitz** [comment]
@spxiwh Wait, no, that was my fault, but I think it will still fail lature. I accidently commited a debug test I was doing on that script to try to see what was happening. Previous failures only errored out when it got to the pegasus validate / plan.

**Comment by spxiwh** [comment]
Where do we install pegasus into these travis builds? It won't come with the pip install pegasus-wms as that doesn't contain the executables (I think)

**Comment by ahnitz** [comment]
@spxiwh It's installed through yum inside the docker_build_dist.sh script. It's only installed for the docker build and not the generic test suite, which just needs the pegasus python api.

**Review by spxiwh — APPROVED** [review]
Putting approval in, as really the only thing needing checking here is if Travis works.

**Pull request merged**
