### PR TITLE
Global ifar plot

### PR DESCRIPTION
**Pull request by GarethDaviesGW**
Adding in global IFAR plot to summary pages

Tested for closed and open boxes, two ifo statmap and multiifo combined statmap

PR #3076 is required in order to produce correct results when hierarchical removal number is not given

Solves issue #2962

### CODE REVIEW

**Comment by tdent** [comment]
do you have a link for the tests?

**Comment by GarethDaviesGW** [comment]
> do you have a link for the tests?

See https://ldas-jobs.ligo.caltech.edu/~gdavies/testoutput/ifar_plot_alltypes/ - all the plots which start with multiifo or twoifo

**Comment by tdent** [comment]
hmm, the closed plots show no useful data so should they be made at all?

the open plots cut off the contours at 10^-4yr, is there a specific reason for that?  are there options for controlling the min ifar plotted and/or the min ifar at which contours exist? 

in the multiifo open plots, what should be the difference between 'hrone' and 'hrnone'?

**Comment by GarethDaviesGW** [comment]
> hmm, the closed plots show no useful data so should they be made at all?

Probably not, I put them in simply as the --open-box argument was vailable and the closed box page_ifar plot was made already - I will remove these from the workflow

> the open plots cut off the contours at 10^-4yr, is there a specific reason for that? are there options for controlling the min ifar plotted and/or the min ifar at which contours exist?

This is an option and would be set in the ini files, I chose 10^4 years ifar as the option that I thought looked prettiest

> in the multiifo open plots, what should be the difference between 'hrone' and 'hrnone'?

this test was to check that they _do_ look the same - hrnone means that no HR level was given as an argument, in which case it defaults to the number of HR removals as given by the attribute in the statmap file, which was 1 in this case

**Pull request merged**
