### PR TITLE
Updating NSBH remnant mass tools

### PR DESCRIPTION
**Pull request by jsantoro392**
- Now using the latest fit from Foucart, Hinderer, Nissanke PRD 98, 081501(R) (2018).
- Removing functions that are no longer needed with the new fit.

### CODE REVIEW

**Comment by spxiwh** [comment]
Hi @jsantoro392 Thanks for this work! I'll assign review of this mostly to @pannarale, however, a few questions/comments from me:

* Can you clarify why we need a `make_grb_uberbank_workflow` executable? Is this mostly the same as the `make_uberbank_workflow` executable, and could this be combined together into one script. (This isn't me saying it should be done one way or the other, but just wanting to understand the choice).
* Please do look over the codeclimate comments, I think most of the things it reports should be fixed and shouldn't be too difficult to do (if the FIXMEs are justified they can stay, but I think the addition of the transformation catalog is a necessary permanent change, so might not need a FIXME ... This would just be an option that would never be provided by a user running the code directly, but in cases like this where a workflow generator is run from within a second workflow generator).

**Comment by pannarale** [comment]
Hi @spxiwh, the changes to the scripts were moved to a second branch.  This makes things cleaner, with this PR dedicated to updating remnant mass functions/utilities and a future PR to creating template banks.  (In this 2nd branch, FIXMEs have been removed and Giada will work on combininr `make_uberbank_workflow` and `make_grb_uberbank_workflow`.)

**Comment by spxiwh** [comment]
@pannarale @jsantoro392 Thanks for splitting this into two PRs ... Separated changes are easier to review. Given the reduced scope, @pannarale should review (as this touches code he manages) and merged when you are both happy.

**Comment by pannarale** [comment]
@spxiwh, is there a way to rerun one of the travis checks?  [This one](https://travis-ci.org/gwastro/pycbc/jobs/626122607?utm_medium=notification&utm_source=github_status) seems to be failing because of a connections time out.

**Pull request merged**
