### PR TITLE
fix distributions import error

### PR DESCRIPTION
**Pull request by soumide1102**
Currently `pycbc_inference` throws an error:
`AttributeError: module 'pycbc' has no attribute 'distributions'`

Fixing how distributions is imported in distributions/utils.py.

### CODE REVIEW

**Review by ahnitz — COMMENTED** [review]
Why would this change do anything?

**Comment by soumide1102** [comment]
@ahnitz I produced that error when running pycbc_inference by hand. I'm mystified as well as to why `import pycbc.distributions as distributions` throws an error. But changing it to `from pycbc import distributions` worked and I could complete a pycbc_inference test with that.

**Comment by soumide1102** [comment]
@ahnitz I reverted the change and the error reappeared. 
(Someone else working with me got that error as well on the NERSC cluster.)

**Comment by ahnitz** [comment]
@soumide1102 Can we follow this up in the slack? I'd like to understand what is happening here

**Comment by soumide1102** [comment]
sure.

**Review by ahnitz — APPROVED** [review]
Ok, I was able to reproduce this by hacking pycbc to install into python3.6 (not a supported python version any longer). In this scenario, we hit he issue only resolved in python3.7 (see https://bugs.python.org/issue30024) related to how circular imports are resolved. 

The change is innocuous for later python versions so I'm happy to approve this.

**Pull request merged**
