### PR TITLE
Preserve input for fftw 

### PR DESCRIPTION
**Pull request by ahnitz**

### CODE REVIEW

**Review by spxiwh — APPROVED** [review]
I'm happy with this ... I definitely think that we don't want FFTW to change the input vector unexpectedly. But @josh-willis might want to comment. The only potential thing is that we might want to consider adding a flag to do non-conserve-input FFTW FFTs for performance (I think a similar option exists in MKL??) Although I'm not sure we have any applications that would use that, so maybe not needed at this stage.

I didn't know that fft_perf.py existed. That's good to know!

**Comment by ahnitz** [comment]
@josh-willis Any objection?

**Comment by josh-willis** [comment]
@ahnitz I'm very opposed to just flipping this switch, since it's done in a way that the user has no way to override. If you want to move forward with this, please do it in a way that allows it to be switched, rather than hard-coding it into how the C library is called.

**Comment by ahnitz** [comment]
@josh-willis Ok, will do.

**Comment by ahnitz** [comment]
@josh-willis Please see the updated PR. Is this what you were looking for?

**Comment by ahnitz** [comment]
@josh-willis Poke

**Comment by ahnitz** [comment]
@josh-willis Poke (sorry, don't know when you are back form vacation. @spxiwh Any idea when we can move forward on this one?

**Review by josh-willis — APPROVED** [review]
I guess I will approve this to avoid holding it up further, but I still don't think this is the right way to handle this.  With this update, the only way to revert to the old behavior is to call an FFTW-specific function, which means programs have to be aware of whether or not they are using the FFTW backend, in addition to being aware enough to know to set that for performance.  It doesn't help that the FFTW docs are unclear what happens if the planning flags are the logical OR of FFTW_DESTROY_INPUT and FFTW_PERSERVE_INPUT, which is certainly possible given that they independently set different bits.

What I think we really need is an optional argument in the class-based interface (I think it's fine to enforce input preservation in function-based; if you care about performance you should be using the class-based interface already).  But that would require modifying not just `fftw.py` but the class-based interface as well, and I just don't have time to carefully think about that right now.

**Comment by ahnitz** [comment]
Noting this is on hold awaiting changes following discussions on a better implementation with @josh-willis. I'll get back to this when my task list is sufficiently clear (so unknown).

**Comment by spxiwh** [comment]
Closing due to long term inactivity. Please reopen if still relevant.

**Pull request closed without merging**
