### PR TITLE
try building wheels

### PR DESCRIPTION
**Pull request by ahnitz**
This PR is an attempt to start building PyCBC binary wheel files. It would be nice for many users not to have to build pycbc directly but to be able to install a pre-built binary. This is an attempt to create those binaries using the 'manylinux' container which is the standard for redistributable linux wheels.

### CODE REVIEW

**Comment by ahnitz** [comment]
Todo:
*  upload wheels to pypi on release
* build wheels for MacOSX

**Comment by ahnitz** [comment]
@spxiwh I'll leave figuring out macos to the future, otherwise, I think this is ready to be reviews. Note that I've moved pypi to its own workflow and out of the basic-tests ones. This means I can't require those pass before this can run, however, as we only merge requests to master and make releases on commits where those tests have already passed, I think this is still safe enough for our purposes.

**Comment by ahnitz** [comment]
Ok, this now *does* build macos wheels as I've moved it to the community standard cibuildwheel tool. 

https://cibuildwheel.readthedocs.io/en/stable/

**Review by spxiwh — APPROVED** [review]
I still don't fully understand all of github actions, but this all looks sane. I guess if problems arise if we try a release it can be resolved afterwards. Thanks.

**Pull request merged**
