### PR TITLE
Update triggers.py to use vectorized time delay

### PR DESCRIPTION
**Pull request by ahnitz**

### CODE REVIEW

**Comment by ahnitz** [comment]
This should improve the performance to be on par with before.

**Comment by tdent** [comment]
I will see if I can test via e.g. pycbc_page_recovery

**Comment by tdent** [comment]
nb - this will be tested by running pycbc_page_recovery at the same time as #2441 .

**Comment by tdent** [comment]
already addressed by #2441 - hence close

**Pull request closed without merging**
