### PR TITLE
WIP: add chip test. compare to lal

### PR DESCRIPTION
**Pull request by Cyberface**
Working on adding a test to compare the chi_p function in pycbc with the lalsuite one.

I don't think I've implemented the test correctly but it's a start.

### CODE REVIEW

**Comment by Cyberface** [comment]
I might not be able to finish this today but on Monday.

**Comment by ahnitz** [comment]
@Cyberface In case you didn't look through. The travis Error is actually from your unit test. 

```
======================================================================
ERROR: test_chip_compare_lalsuite (__main__.TestParams)
Compares effective precession parameter bewteen
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_conversions.py", line 156, in test_chip_compare_lalsuite
    self.spin2x, self.spin2y, self.spin2z, 2)
TypeError: in method 'SimIMRPhenomPCalculateModelParametersFromSourceFrame', argument 8 of type 'REAL8'

----------------------------------------------------------------------
Ran 3 tests in 0.241s
```

**Comment by ahnitz** [comment]
@Cyberface Is this still a WIP?

**Comment by Cyberface** [comment]
@ahnitz no this is finished now.

Linking to this issue https://github.com/gwastro/pycbc/issues/2247 where it has also been discussed. That issue can be closed if people are happy with this MR.

**Comment by tdent** [comment]
@cdcapano @Cyberface please either approve and merge this PR or close it.  Trying to reduce the total number of open PRs

**Pull request merged**
