### PR TITLE
Support for generating time varying noise 

### PR DESCRIPTION
**Pull request by sum33it**
A support for generating a time varying noise is added. With the help of an additional argument `scale` (default = 1.0), one can generate a time varying noise where total time can be broken into smaller equal chunks (time bins) and an array of scale values for each bin can be provided which act as the time varying function. Then time series generated from all the bins can be stacked together. The seed should be same for all the bins.

While generating the coloured noise, white noise is multiplied with the ASD. The `scale` argument is multiplicative factor to ASD. A more general frequency dependent function can be added in future.

### CODE REVIEW

**Comment by titodalcanton** [comment]
How related is this to #3825?

**Comment by sum33it** [comment]
@titodalcanton This is a parallel approach to #3825 which requires minimal changes in current infrastructure to produce a simple time varying PSD.

**Comment by sum33it** [comment]
@ahnitz Poke.

**Review by ahnitz — APPROVED** [review]

**Comment by ahnitz** [comment]
@sum33it please reabse and fix the history

**Review by ahnitz — APPROVED** [review]

**Pull request merged**
