### PR TITLE
PSD variation Ranking statistics 

### PR DESCRIPTION
**Pull request by sum33it**
Added two ranking statistics which takes PSD variation into account:
i) phasetd_exp_fit_stat_sgveto_psdvar_scaled,
ii) exp_fit_stat_sgveto_psdvar

### CODE REVIEW

**Comment by tdent** [comment]
Sumit, after the reorganization of #2602 the `get_newsnr_sgveto_psdvar_scaled(trigs)` function should now be placed in `pycbc/events/ranking.py` where the other get_newsnr - like functions now live.

**Comment by tdent** [comment]
Also can you reformat any lines of code which are significantly over 80 chars long (see the codeclimate 'Details' link

**Comment by spxiwh** [comment]
Is this still active?

**Comment by tdent** [comment]
Can this now be closed - @ahnitz @sum33it @spxiwh ?

**Comment by tdent** [comment]
ping @sum33it @ahnitz - can we close this please?

**Pull request closed without merging**
