### PR TITLE
Added pycbc_make_skymap

### PR DESCRIPTION
**Pull request by Fergus-Hayes**
Added a new executable `bin/pycbc_make_skymap` that quickly produces sky localization given a the time, masses and spins of a trigger by utilizing a single template matched filter on strain data from a number of detectors. The sky localization is produced from the resulting SNR time series using BAYESTAR and therefore the user requires `ligo.skymap`installed in their environment. The script outputs a .png file and a .fits file of the skymap as well as an .xml file containing the SNR timeseries.

### CODE REVIEW

**Comment by titodalcanton** [comment]
Also look into `setup.py`, I think the script must be listed there, otherwise it will not be installed.

**Comment by titodalcanton** [comment]
Ah nevermind, it looks like `setup.py` just installs every appropriate file under `/bin/` now

**Comment by Fergus-Hayes** [comment]
@titodalcanton Although the tests seem to fail as `ligo.gracedb` is not installed. However I see `ligo-gracedb` is listed in `companion.txt`. Are these packages from `companion.txt` not installed from `setup.py`? If not should `setup.py` be altered to install the `ligo.gracedb` package?

Also will the tests pass given that `ligo.skymap` is required although not imported?

**Comment by titodalcanton** [comment]
Please add the new script to the list of test exceptions [here](https://github.com/gwastro/pycbc/blob/master/tools/pycbc_test_suite.sh#L33). We have other scripts that require GraceDB, so the strategy for now is just to skip those tests.

**Comment by titodalcanton** [comment]
I just had the same exact issue on another PR :) Another solution is to move the GraceDB import to where it is actually needed, so the current test will not actually try it.

**Comment by micamu** [comment]
@Fergus-Hayes Could you fix the help message in line 305 before merging? It should request just one single time (which is what the code takes now). If you want the user to give a dictionary of trigger times you need to make a few changes to the main function

**Comment by ahnitz** [comment]
@titodalcanton Any reason this hasn't been merged?

**Pull request merged**
