### PR TITLE
PyCBC Live: fix bug in mechanism that prevents multiple uploads

### PR DESCRIPTION
**Pull request by titodalcanton**
Fixes a couple bugs introduced in #3984. I have tested that uploads work after this. We do need a way to try some kind of fake uploads in our test suite though.

### CODE REVIEW

**Comment by GarethCabournDavies** [comment]
> We do need a way to try some kind of fake uploads in our test suite though.

Changes look good to me - any ideas on how to implement this in the test suite?

**Review by GarethCabournDavies — APPROVED** [review]

**Comment by ahnitz** [comment]
@GarethCabournDavies Is the gdb server code public so one can just start up a test instance in the CI?

**Comment by GarethCabournDavies** [comment]
> @GarethCabournDavies Is the gdb server code public so one can just start up a test instance in the CI?

I didn't think it was,but looks like it might be [here](https://git.ligo.org/computing/gracedb/server). I won't pretend to be anywhere near able to understand how to implement it though!

**Comment by titodalcanton** [comment]
@ahnitz I have been wondering the same actually. As far as I know it is a Django setup, so in principle it should even be possible to spin up an instance using an sqlite3 backend. I can have a look in the coming weeks.

**Pull request merged**
