### PR TITLE
more physical rwrap for LISA SMBHB/SOBHB injection

### PR DESCRIPTION
**Pull request by WuShichao**
@ahnitz This PR uses the damping time of (2,2) QNM of ringdown from the injected signal to set `rwrap`, now the time-domain injection for SMBHB and SOBHB works fine:

(1) SMBHB (and its zoom-in)
smbhb
smbhb_zoomin

(2) SOBHB:
sobhb

### CODE REVIEW

**Comment by WuShichao** [comment]
@ahnitz As you suggested, I separated some code from https://github.com/gwastro/pycbc/pull/4289 to merge.

**Comment by WuShichao** [comment]
I move `pykerr` from `companion.txt` to `requirements.txt`, because we will encouter this error in build test:
```
Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.8.16/x64/bin/pycbc_inspiral", line 230, in <module>
    gwstrain = strain.from_cli(opt, dyn_range_fac=DYN_RANGE_FAC,
    File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/strain/strain.py", line 312, in from_cli
    injector.apply(strain, opt.channel_name.split(':')[0],
    File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/inject/inject.py", line 570, in apply
    signal = self.make_strain_from_inj_object(inj, delta_t,
    File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/inject/inject.py", line 637, in make_strain_from_inj_object
    hp, hc = get_td_waveform(inj, delta_t=delta_t, f_lower=f_l,
    File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/waveform/waveform.py", line 598, in get_td_waveform
    return wav_gen(**input_params)
    File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/waveform/waveform.py", line 847, in get_td_waveform_from_fd
    return _base_get_td_waveform_from_fd(None, rwrap, **params)
    File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/waveform/waveform.py", line 766, in _base_get_td_waveform_from_fd
    rwrap = tau_from_final_mass_spin(m_final, spin_final) * 8
    File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/conversions.py", line 1034, in tau_from_final_mass_spin
    return get_lm_f0tau(final_mass, final_spin, l, m, n=n, which='tau')
    File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/conversions.py", line 942, in get_lm_f0tau
    taus = pykerr.qnmtau(mass, spin, l, m, n)
    File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/libutils.py", line 235, in __getattribute__
    raise ImportError(inspect.cleandoc(msg))
ImportError: The function get_lm_f0tau tried to access
    'qnmtau' of library 'pykerr', however,
'pykerr' is not currently installed. To enable this
functionality install 'pykerr' (e.g. through pip
/ conda / system packages / source).
```

**Comment by ahnitz** [comment]
@WuShichao Can you check this also works for ligo mass sources as well? i.e. check that masses 2-1000 are also ok.

**Review by ahnitz — COMMENTED** [review]
This looks OK, just a final check would be helpful before merging.

**Comment by ahnitz** [comment]
> 

Please don't do this. You aren't adding a hard dependence on it are you? If so, we should think about that a bit more to see if rearrangement is needed.

**Comment by ahnitz** [comment]
> I move `pykerr` from `companion.txt` to `requirements.txt`, because we will encouter this error in build test:
> 
> ```
> Traceback (most recent call last):
>     File "/opt/hostedtoolcache/Python/3.8.16/x64/bin/pycbc_inspiral", line 230, in <module>
>     gwstrain = strain.from_cli(opt, dyn_range_fac=DYN_RANGE_FAC,
>     File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/strain/strain.py", line 312, in from_cli
>     injector.apply(strain, opt.channel_name.split(':')[0],
>     File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/inject/inject.py", line 570, in apply
>     signal = self.make_strain_from_inj_object(inj, delta_t,
>     File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/inject/inject.py", line 637, in make_strain_from_inj_object
>     hp, hc = get_td_waveform(inj, delta_t=delta_t, f_lower=f_l,
>     File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/waveform/waveform.py", line 598, in get_td_waveform
>     return wav_gen(**input_params)
>     File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/waveform/waveform.py", line 847, in get_td_waveform_from_fd
>     return _base_get_td_waveform_from_fd(None, rwrap, **params)
>     File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/waveform/waveform.py", line 766, in _base_get_td_waveform_from_fd
>     rwrap = tau_from_final_mass_spin(m_final, spin_final) * 8
>     File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/conversions.py", line 1034, in tau_from_final_mass_spin
>     return get_lm_f0tau(final_mass, final_spin, l, m, n=n, which='tau')
>     File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/conversions.py", line 942, in get_lm_f0tau
>     taus = pykerr.qnmtau(mass, spin, l, m, n)
>     File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/libutils.py", line 235, in __getattribute__
>     raise ImportError(inspect.cleandoc(msg))
> ImportError: The function get_lm_f0tau tried to access
>     'qnmtau' of library 'pykerr', however,
> 'pykerr' is not currently installed. To enable this
> functionality install 'pykerr' (e.g. through pip
> / conda / system packages / source).
> ```

Hmm, we should check why this is. We don't want to add a hard dependency unless really required. Do you know where is this coming from?

**Comment by WuShichao** [comment]
@ahnitz For the ground-based detectors, I increased the factor to `t_damping = tau_from_final_mass_spin(m_final, spin_final) * 10`, and used the below code to test:
```
import matplotlib.pyplot as pp
from pycbc import waveform

# Get a frequency domain waveform
hp_IMRPhenomPv2, hc_IMRPhenomPv2 = waveform.get_td_waveform_from_fd(approximant="IMRPhenomPv2",
                                    mass1=50, mass2=50, delta_t=1.0/4096, f_lower=20)

pp.plot(hp_IMRPhenomPv2.sample_times, hp_IMRPhenomPv2, label="IMRPhenomPv2 (IFFT)")

# pp.title("mass1=1.4, mass2=1.4")
# pp.title("mass1=500, mass2=500")
pp.title("mass1=50, mass2=50")
pp.ylabel('Strain')
pp.xlabel('Time (s)')
pp.legend()
pp.show()
```
bns
bns_zoomin
stellar_bbh
imbh

**Comment by WuShichao** [comment]
> > I move `pykerr` from `companion.txt` to `requirements.txt`, because we will encouter this error in build test:
> > ```
> > Traceback (most recent call last):
> >     File "/opt/hostedtoolcache/Python/3.8.16/x64/bin/pycbc_inspiral", line 230, in <module>
> >     gwstrain = strain.from_cli(opt, dyn_range_fac=DYN_RANGE_FAC,
> >     File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/strain/strain.py", line 312, in from_cli
> >     injector.apply(strain, opt.channel_name.split(':')[0],
> >     File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/inject/inject.py", line 570, in apply
> >     signal = self.make_strain_from_inj_object(inj, delta_t,
> >     File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/inject/inject.py", line 637, in make_strain_from_inj_object
> >     hp, hc = get_td_waveform(inj, delta_t=delta_t, f_lower=f_l,
> >     File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/waveform/waveform.py", line 598, in get_td_waveform
> >     return wav_gen(**input_params)
> >     File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/waveform/waveform.py", line 847, in get_td_waveform_from_fd
> >     return _base_get_td_waveform_from_fd(None, rwrap, **params)
> >     File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/waveform/waveform.py", line 766, in _base_get_td_waveform_from_fd
> >     rwrap = tau_from_final_mass_spin(m_final, spin_final) * 8
> >     File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/conversions.py", line 1034, in tau_from_final_mass_spin
> >     return get_lm_f0tau(final_mass, final_spin, l, m, n=n, which='tau')
> >     File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/conversions.py", line 942, in get_lm_f0tau
> >     taus = pykerr.qnmtau(mass, spin, l, m, n)
> >     File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycbc/libutils.py", line 235, in __getattribute__
> >     raise ImportError(inspect.cleandoc(msg))
> > ImportError: The function get_lm_f0tau tried to access
> >     'qnmtau' of library 'pykerr', however,
> > 'pykerr' is not currently installed. To enable this
> > functionality install 'pykerr' (e.g. through pip
> > / conda / system packages / source).
> > ```
> 
> Hmm, we should check why this is. Do you know where is this coming from? Is there an obvious away to avoid this as a hard requirement?

In the build test `inspiral-BBH_INJECTIONS-H1_118674`, it seems we have to use this `pykerr` function, I'm not sure if lal has a similar one.

**Comment by ahnitz** [comment]
@WuShichao If you need to depend on pykerr you have to add it to setup.py as well, otherwise the tests will fail. 

The alternative is to just use a heuristic like before but have it scale with total mass. That would no need the dependency. What do you think? 

I think pykerr is not a completely perfect solution either as some signals in principle could be BNS and would have a very different ringdown. Any choice here is somewhat adhoc.

**Comment by WuShichao** [comment]
> @WuShichao If you need to depend on pykerr you have to add it to setup.py as well, otherwise the tests will fail.
> 
> The alternative is to just use a heuristic like before but have it scale with total mass. That would no need the dependency. What do you think?
> 
> I think pykerr is not a completely perfect solution either as some signals in principle could be BNS and would have a very different ringdown. Any choice here is somewhat adhoc.

I prefer a more physical solution :) When we want to do the time-domain BNS poster-merger injection, we can add a post-merger duration estimator in the future.

**Comment by ahnitz** [comment]
@WuShichao You'll need to rebase from master. See discussion in pycbc-code channel for why.

**Comment by ahnitz** [comment]
@WuShichao If pykerr is a hard dependency, pykerr must be listed in setup.py.

**Review by ahnitz — APPROVED** [review]

**Pull request merged**
