### PR TITLE
Add decimation to sngls_findtrigs

### PR DESCRIPTION
**Pull request by GarethCabournDavies**
This change adds decimation into the `pycbc_sngls_findtrigs` code

## Standard information about the request

This is a new feature/efficiency change
This change affects the offline search
This changes result presentation / plotting, and has slight effects on scientific output (these should be negligible)
This change follows style guidelines and has been proposed using the contribution guidelines

## Motivation
We saw that the sngls_statmap job was using a lot of memory - part of this was as the sngls_findtrigs jobs were saving _everything_, even when the events had no chance of being real, or included in the significance fitting.

## Contents
Events are decimated below certain thresholds in the sngls_findtrigs code. This is done by using successive factors and statistic thresholds, and only keeping events with statistic below the threshold if the `trigger_id` is an integer multiple of the factor (multiplied by any previous factors).

This is the same as is done in the coinc jobs except that it is the `trigger_id` which is used to decide on decimation rather than the `timeslide_id`. I don't think this will add any bias.

## Links to any issues or associated PRs
A hotfix was applied to the v23 release branch in https://github.com/gwastro/pycbc/pull/4732

This solution is a bit nicer than the one in #4732 - basically this allows us to still see the diustribution to lower statistic values when plotting, which enables us to tweak the significance fit threshold

## Testing performed
The sngls_findtrigs from an O4 chunk were calculated, and then the statmap job was run, the pycbc_page_snrifar for these is here (LVK paywall):
[decimated](https://ldas-jobs.ligo.caltech.edu/~gareth.cabourndavies/testoutput/sngls_statmap_efficiency/testing/output/H1-SNGLS_STATMAP_decimated.png) vs [original](https://ldas-jobs.ligo.caltech.edu/~gareth.cabourndavies/testoutput/sngls_statmap_efficiency/testing/output/H1-SNGLS_STATMAP.png)

Decimation levels for this test are `[0:10,-2.5:10,-5:10,-10:10,-20:999999]`

We see that the behaviour above stat around -2.5 is the same, but we get extra (once we account for decimation) events below this.

I think the 'extra' events are due to not being clustered away post-decimation, which means that we actually see the distribution to lower statistic values!

We also used a fit threshold of -1.2 in the statmap code, so we see that the significance fitting works even when the fit threshold is below the decimation thresholds

## Additional notes
We also fix a bug in the significance module:
 - things below the threshold were not using the correct decimation for the count_n_louder switch - this has been fixed
 - This was not seen before as in all use-cases, the decimation was the same (1) for every event, so grabbing the wrong decimation value had no effect

- [x] The author of this pull request confirms they will adhere to the [code of conduct](https://github.com/gwastro/pycbc/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by spxiwh** [comment]
I'm not sure I'm going to say anything meaningful from staring at the code, so wanted to review from the plots. However, it is hard to compare the before/after plot or check that things are unchanged above a stat of 0. Is it possible to make some easier to digest comparison plots?

**Comment by GarethCabournDavies** [comment]
https://ldas-jobs.ligo.caltech.edu/~gareth.cabourndavies/testoutput/sngls_statmap_efficiency/testing/output/L1-SNGLS_STATMAP_COMPARE.png shows the IFAR vs statistic plots for the decimated / undecimated cases outputs, with the difference in the right hand plot, we see that there is <1e-6 fractional difference in FAR (the green points) for all points above statistic zero.

If using decimation which has a one of the decimation thresholds above the fit threshold, we see https://ldas-jobs.ligo.caltech.edu/~gareth.cabourndavies/testoutput/sngls_statmap_efficiency/testing/output/H1-SNGLS_STATMAP_COMPARE.png, which I think is within statistical variation for the alpha parameter

**Comment by spxiwh** [comment]
I don't understand the second plot. Shouldn't it have no difference for statistic above 0?

For the first plot, should we not correct the decimation (as we do for coinc triggers), rather than having the two lines diverge?

**Comment by GarethCabournDavies** [comment]
Sorry, I should have been more explicit:
Both links use decimation levels of `[0:10,-2.5:10,-5:10,-10:10,-20:999999]`

The first link (L1) uses a fit threshold of 0, the second link (H1) uses a fit threshold of -1.2.

So the L1 case, we see that everything above 0 has negligible (I set the zero values to 1e-6 so that the scatter points would show on a log scale)

In the H1 case, as we have some decimation above the -1.2 threshold, the fit outcome is different, so we see that the FAR changes, but it is just the difference of two straight lines at this point, I think this is within the noise of the fit.

I've added lines to the plot to show the fit and decimation thresholds, and updated to show the points which are exactly zero difference, rather than simply below 1e-6 in the L1 plot.

There are a few values with slight difference, but I dont think these really matter

**Comment by GarethCabournDavies** [comment]
The differences below the fit threshold point are, I think, due to the clustering of events.

These use the same method of FAR calculation as coincs.

When these are un-decimated, the largest within a window is chosen, but as some of these are decimated away, the largest in the cluster window follows the exponential fit down to a lower value.

**Review by spxiwh — APPROVED** [review]
We discussed this, and I am happy with the changes made.

**Pull request merged**
