### PR TITLE
Move hdfcoinc plotting executables to plotting

### PR DESCRIPTION
**Pull request by spxiwh**
I'm pulling off parts of #3535 that can be merged before before updating `stat.py`. The first thing I need to merge is a couple of rearrangment commits. This PR rearranges the code in the `hdfcoinc` directory by:

 * Moving any plotting code into the `plotting` directory. A bunch of stuff in here had nothing to do with hdfcoinc anyway. We could further organize the plotting directory if needed in the future.

 * Move the remaining contents into a new directory called `all_sky_search.

### CODE REVIEW

**Comment by ahnitz** [comment]
@spxiwh Doesn't look the second bullet has made it in yet, no?

**Comment by ahnitz** [comment]
@spxiwh I.E. I don't see any renaming to 'all_sky_search' in your PR atm.

**Comment by spxiwh** [comment]
Oops! Sorry, I changed my mind about having that as two separate PRs. It's added now.

**Review by ahnitz — APPROVED** [review]
It's all just moving the folders around in bin. I have no objections to this scheme and the change should be trivial to the functioning of pycbc (since this is all flattened upon install).

**Comment by spxiwh** [comment]
Indeed. I wanted to do this and get it in *before* the next PR, which will be removing/renaming all the coinc executables.

**Comment by tdent** [comment]
Ah, this is why all the old links I have stored in my browser for plotting codes suddenly give 404 ... 
Can users please be given some general overview of any major reorganization of the code directory structure in the pycbc-code channel?

**Pull request merged**
