### PR TITLE
Add script to do basic operations and reranking of single trigger files

### PR DESCRIPTION
**Pull request by tdent**
Labelled 'work in progress' as it hasn't yet been tested for a full range of ranking stats. 

Also I'm not sure if the vetoing and cutting and clustering filters are correct and/or all play nicely with each other - this may need some thought.  Initial tests seem reasonable as compared to applying cuts while plotting (in the pycbc_plot_singles_vs_params script)

### CODE REVIEW

**Comment by spxiwh** [comment]
Hi @tdent I've been testing this and noticed two things:

* The stat calculation was bugged as you weren't using the mask, so were calculating stats for the unmasked triggers and then taking the first N.
* You needed a little bit more poking to make exp_fit single statistics work.

I've just opened a pull request to fix both of these things. The stat calculation is still really inefficient, but I think we'd need something tricksy to deal with this (ie create a subclassed dictionary-like object to intercept `trigs['snr']` and replace it with `trigs['snr'][self.mask]`). Maybe that's overoptimization though, unless we actually need that speed.

**Comment by spxiwh** [comment]
I also plan to add an option to also dump the bank parameters into the file

**Comment by spxiwh** [comment]
@tdent I've added an option to dump the bank parameters to the pull request onto this branch

**Comment by tdent** [comment]
@spxiwh the way to evaluate stats efficiently is to do it on a file with a small number of triggers which you prepared earlier by doing a simple cut ..

**Comment by tdent** [comment]
@spxiwh do you think it's worthwhile storing non-existent filter functions or cluster windows as 'None' rather than just not giving the output file that attribute?

**Comment by tdent** [comment]
@spxiwh if you put in an approving review this can be merged, the codeclimate badness is just the word 'FIXME'.

**Pull request merged**
