### PR TITLE
pick max singles by network SNR

### PR DESCRIPTION
**Pull request by ahnitz**
For a coincident event use the loudest (by network SNR) singles information for followup.

### CODE REVIEW

**Comment by tdent** [comment]
It looks like this defines 'network' SNR as the sum over 2 coinc triggers, ie not including additional detectors - yes?

When you say followup what does that mean, btw?

**Comment by tdent** [comment]
(& Codeclimate seems pretty unhappy with this)

**Comment by titodalcanton** [comment]
I am wondering if we want a command-line option to choose between the old and new behavior, since (if I understand correctly) the change affects the choice of which template is used for the p-value in the followup detectors, and thus the FAR/sensitivity of the search.

**Comment by ahnitz** [comment]
I no longer think this is is the best approach so am closing for now.

**Pull request closed without merging**
