### PR TITLE
set TDI version in LDC example

### PR DESCRIPTION
**Pull request by WuShichao**
## Standard information about the request

This is a: bug fix

This change affects: Set TDI version for the upcoming BBHx plugin update.

This change changes: documentation,

- [x] The author of this pull request confirms they will adhere to the [code of conduct](https://github.com/gwastro/pycbc/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by ahnitz** [comment]
@WuShichao Why is this a bugfix? Shoudn't there be a default value?

**Review by ahnitz — APPROVED** [review]

**Comment by WuShichao** [comment]
> @WuShichao Why is this a bugfix? Shoudn't there be a default value?

Set a default value is not a good idea, because initially I set it to be '1.5'. If I set TDI to be '2.0' but sometimes I forget to set it in the PE config file, results will be wrong, I guess users will encounter the same problem, so I just force users to set it.

**Comment by ahnitz** [comment]
@WuShichao I'm not sure this should be a required argument. On the plugin side, it probably should have a default and one can optionally change the value.

**Comment by WuShichao** [comment]
> @WuShichao I'm not sure this should be a required argument. On the plugin side, it probably should have a default and one can optionally change the value.

Just set it by default on one side, but not on other side, might be inconsistent. Currently we don't have a check in PyCBC Inference to make sure the TDI versions are consistent everywhere, this will cause problem, and users will likely miss the point.

**Pull request merged**
