### PR TITLE
Cache lal builds based on hash, update lal hash, and add ligo-segments

### PR DESCRIPTION
**Pull request by duncan-brown**
Add the name of the lalsuite hash to the cache file that build E@H uses and only use that (and the other cache tarballs) if the hash matches.

Will need someone to change the lalsuite hash to test. @spxiwh can you set the hash to a version that doesn't have broken EOB or similar to test?

### CODE REVIEW

**Comment by duncan-brown** [comment]
@spxiwh :poke:

**Comment by spxiwh** [comment]
This is a pain to test because there's still cached products. I need a way to clear cached products in the Travis builds. Does this exist?

**Comment by duncan-brown** [comment]
@spxiwh GWR WiFi munged that last commit, so trying again. I want to do the tests that you suggested on this branch, so hold off merging for the moment.

**Comment by duncan-brown** [comment]
OK, the first build [cached lalsuite](https://travis-ci.org/gwastro/pycbc/jobs/404906958#L3533) with the tag, the next build [failed to find the right hash](https://travis-ci.org/gwastro/pycbc/jobs/405913497#L712) with the new hash [build failed](https://travis-ci.org/gwastro/pycbc/jobs/405913497#L2428) `ImportError: No module named ligo` as expected, so it really did grab the new lal.

**Pull request merged**
