### PR TITLE
Fix pruning for single templates

### PR DESCRIPTION
**Pull request by connor-mcisaac**
When using a single template in the offline workflow you get a ZeroDivision error in the fit singles code.
This is because the minimum and maximum of the pruning parameters are equal, and in the method "which_bin" it divides by "float(maxpar - minpar)".
This PR shifts these limits slightly to avoid errors.

### CODE REVIEW

**Comment by tdent** [comment]
I'm not sure this is fixing in the right place - could it not be more basically addressed by putting in a try-except here https://github.com/gwastro/pycbc/blob/master/pycbc/events/trigger_fits.py#L244 
with a comment like "corner case : if binning only one value an identical min/max may be obtained, avoid division by 0"
basically, we should only 'hack' the min/max values if and when necessary.

**Comment by connor-mcisaac** [comment]
Yeah, could put in an if statement "if minpar == maxpar: frac = 0" to avoid try-excepts.

**Comment by tdent** [comment]
or even frac = 0.5 (as it would be when shifting min and max by equal and opposite amounts) .. anyway, yes, I think the `if` approach is more transparent and maintainable

**Comment by tdent** [comment]
Looks OK. It may be worth checking that we don't expect the function to work with a numpy array input - I am guessing we don't.

**Comment by tdent** [comment]
(i.e. I guess it would be nice to have this function work for 'par' being a numpy array, but I assume that is currently optional)

**Comment by connor-mcisaac** [comment]
It doesn't seem to be intended to take an array at the moment as "float(par - minpar)" would through an error for an array.

**Pull request merged**
