### PR TITLE
Ambi chisq support

### PR DESCRIPTION
**Pull request by bhooshan-gadre**
# Added ambiguity chisq functionality:
1. Ambiguity chi-sq added to inspiral code.
2. FilterBank class can now cache 'n' filters if needed.
3. Tested and works fine with real and simulated data. Also works as expected if this chi-sq is not used.

## Some more documentation and test examples to follow.

### CODE REVIEW

**Comment by ahnitz** [comment]
@bhooshan-gadre I may have time to look at this later this week, but please address the CC issues. You may find the 'black' package useful to automatically fix most of these issues. 

https://github.com/psf/black

**Comment by bhooshan-gadre** [comment]
> @bhooshan-gadre I may have time to look at this later this week, but please address the CC issues. You may find the 'black' package useful to automatically fix most of these issues.
> 
> https://github.com/psf/black
Thanks. I will try and use it to fix codeclimate issues.

**Comment by spxiwh** [comment]
Thanks @bhooshan-gadre ! I wanted to ask about how much duplication there is between the ambi chisq, and the existing bank chi-squared? If the additional functionality here is the ability to orthonormalize the various bank filters, I don't think we want two separate chi-squareds when this could perhaps be implemented as options to a single ambi/bank_chisq module. If this new method is obviously better, than perhaps we just remove the old method?

Can this be implemented so that we don't have separate bank- and ambi-chisq modules?

**Comment by bhooshan-gadre** [comment]
> Thanks @bhooshan-gadre ! I wanted to ask about how much duplication there is between the ambi chisq, and the existing bank chi-squared? If the additional functionality here is the ability to orthonormalize the various bank filters, I don't think we want two separate chi-squareds when this could perhaps be implemented as options to a single ambi/bank_chisq module. If this new method is obviously better, than perhaps we just remove the old method?
> 
> Can this be implemented so that we don't have separate bank- and ambi-chisq modules?

I have to check that. I will have a look and try to combine bank and ambi-chisq if possible.

**Comment by ahnitz** [comment]
@bhooshan-gadre What is the status of this PR? Have you abandoned it?

**Comment by spxiwh** [comment]
Closing due to long-term inactivity. Please reopen if still needed.

**Pull request closed without merging**
