### PR TITLE
Injection and foreground minifollowups missing triggers/data

### PR DESCRIPTION
**Pull request by GarethDaviesGW**
timefreq and qscan plots were being shown as blank plots in the case where the -1 sentinel value was found, whether data was available or not

For example for a HL coinc, the V qscan and timefreq were blank, even if V was running but did not trigger

Given these changes the minifollowup workflow creation now takes the mean time from the other detectors, and tries to create the plots. If they fail, as the time is outside of analysis time in that detector, then the plot will simply not be made.

This is a point where I ask whether we would _prefer_ a blank plot to show definitively that there is no data (or a standard 'this IFO has no data" image?)

This PR helps address #2882

### CODE REVIEW

**Comment by GarethDaviesGW** [comment]
Results page is available at:

https://ldas-jobs.ligo.caltech.edu/~gdavies/analyses/multiifodev/test_workflow_minifollowup/

This page is missing singles followup results, but I believe this is unrelated to the changes made

**Comment by spxiwh** [comment]
@GarethDaviesGW I'm not really sure what happens here in the case that the third ifo has no data (or the data is not valid). There is no check in the workflow generator (that I know of) to ensure that these plots are running on valid data. So how does this not end up with jobs either making q-scans of not-data-at-all, or potentially failing if the data is not there at all??

**Comment by GarethDaviesGW** [comment]
In minifollowup.py, make_qscan_plot has a check for if the time is in analysis segments, and raises a ValueError: https://github.com/gwastro/pycbc/blob/master/pycbc/workflow/minifollowups.py#L667

The same check is available for the timefreq plot in https://github.com/gwastro/pycbc/blob/master/pycbc/workflow/minifollowups.py#L768

This makes it fairly easy to simply do a try-except (i.e. thank you very much Ian from 2 years ago!)

**Comment by spxiwh** [comment]
@GarethDaviesGW Okay, I see. There's some nasty edge cases here though, as this is not using the "was the data analysed" flag ... Data in the 8s buffer region for example would make a plot, when it shouldn't. Let me make some in-code comments to suggest how to do this a little differently. There is still the question of CAT_2 vetoes though. If the data is vetoed, should we make a plot?

**Comment by spxiwh** [comment]
Apparently, I can't do this in-line, but here:

https://github.com/gwastro/pycbc/pull/2913/files#diff-b6afb4936883333e4f74f69a8d36e144L96

the `insp_data_seglists` is created. Can you *also* create a `insp_analysed_seglists`, using identical logic, but using `args.inspiral_data_analyzed_name` instead of `args.inspiral_data_read_name`.

Then you can use the same check as the one you pointed to, but put it upfront in the `minifollowup` executables and have it check `insp_analysed_seglists` not `insp_data_seglists`.

Does that all make sense? ... I think if you want to also exclude CAT_2 times you'd have to read the segment data directly from the STATMAP file, instead of from the XML file currently used.

**Comment by GarethDaviesGW** [comment]
Makes sense on the face of it. I will have a look when I can

**Comment by GarethDaviesGW** [comment]
I think this correctly addresses @spxiwh 's suggestions. The CAT2 times I think I will leave in as they should be shown with the green hashing (or am I missing this point?)

**Pull request merged**
