### PR TITLE
remove the old pylal sensitivity code

### PR DESCRIPTION
**Pull request by ahnitz**
Note that I've assigned both @tdent and @spxiwh to review this change.

This removes the old pylal sensitivity by binning code. We don't use this for published VT statements at the moment, but it is the default for diagnostic plots. We should move to using one of the other available methods we already have implemented.

### CODE REVIEW

**Comment by tdent** [comment]
@ahnitz We don't have any reviewed VT code in the pipeline at the moment.  That is due both to the standard plotting codes not incorporating redshift, and Vaibhav's code not being reviewed yet.  In any case this method is simple, comprehensible and may be useful as a comparison for other methods. 
Also I don't know why I would have been asked to remove external pylal dependences but keep the pylal style VT, which was somewhat nontrivial to do, if people intended to discard it in the medium term. 
Also I think bin_utils is used elsewhere in pycbc. 
So, I do not support doing this.

**Comment by ahnitz** [comment]
The closest replication of the pylal method is the 'shell' one which makes the same assumtions about distributions, but doesn't chop up into explicit bins.

```
integration-method=shell
```

For many cases, this will be the right change to the config files, and will give volumetric VT estimate, assuming injections were done with a chirp_distance distribution.
```
integration-method = mc
distance-param = chirp_distance
limits-param = chirp_distance
distribution = uniform
```

**Comment by tdent** [comment]
FIRST: bin_utils.py is used by other codes and may be generally useful for plotting, don't remove it. 

SECOND: rate.py contains functions that are generally useful for integrating and making confidence intervals in 1d pdfs and have been reviewed as such (e.g. were used in some pre-O1 upper limit results).  Don't remove it wholesale.  The diff should only remove the functions needed for the binned volume calculation.  And might we ever want to plot efficiency vs distance at some point?  Ie will compute_efficiency() never be useful?

To approve I would need to see comparisons of 'shell' vs 'pylal' and check that difference(s) between them would not lead us to significantly wrong conclusions when comparing plots made with different methods.  If we remove one method then how will people compare VT between old runs made with a no longer existent method, and new runs?

**Comment by spxiwh** [comment]
Inactive for over a year. Closing.

**Pull request closed without merging**
