### PR TITLE
based duration on template length

### PR DESCRIPTION
**Pull request by ahnitz**

### CODE REVIEW

**Comment by ahnitz** [comment]
@titodalcanton This might help. I'm not sure I can test this probably at the moment though.

**Comment by titodalcanton** [comment]
Testing.

**Comment by titodalcanton** [comment]
It seems to change the numbers but not solve the issue:
```
2019-03-15 11:04:59,997 node742 computing followup data for coinc
2019-03-15 11:04:59,999 node742 Generating SPAtmplt, 88.0s, 173289, starting from 25.1 Hz
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tito/projects/pycbc/live/multidetector/env/lib/python2.7/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/home/tito/projects/pycbc/live/multidetector/env/lib/python2.7/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/home/tito/projects/pycbc/live/multidetector/env/lib/python2.7/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib64/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tito/projects/pycbc/live/multidetector/env/bin/pycbc_live", line 629, in <module>
    data_reader, bank)
  File "/home/tito/projects/pycbc/live/multidetector/env/bin/pycbc_live", line 181, in check_coincs
    data_readers, bank, followup_ifos)
  File "/home/tito/projects/pycbc/live/multidetector/env/bin/pycbc_live", line 134, in compute_followup_data
    data_readers[ifo], bank, template_id, coinc_times)
  File "/home/tito/projects/pycbc/live/multidetector/env/lib/python2.7/site-packages/pycbc/filter/matchedfilter.py", line 1773, in followup_event_significance
    if not data_reader.state.is_extent_valid(state_start_time, bdur):
  File "/home/tito/projects/pycbc/live/multidetector/env/lib/python2.7/site-packages/pycbc/frame/frame.py", line 745, in is_extent_valid
    data = self.raw_buffer[s:e]
  File "</home/tito/projects/pycbc/live/multidetector/env/lib/python2.7/site-packages/decorator.pyc:decorator-gen-120>", line 2, in __getitem__
  File "/home/tito/projects/pycbc/live/multidetector/env/lib/python2.7/site-packages/pycbc/types/array.py", line 67, in _convert
    return fn(self, *args)
  File "/home/tito/projects/pycbc/live/multidetector/env/lib/python2.7/site-packages/pycbc/types/array.py", line 799, in __getitem__
    return self._getslice(index)
  File "/home/tito/projects/pycbc/live/multidetector/env/lib/python2.7/site-packages/pycbc/types/timeseries.py", line 106, in _getslice
    ' not supported').format(index.start))
ValueError: Negative start index (-6737) not supported
```

**Comment by titodalcanton** [comment]
@ahnitz I just pushed a fix that I think is necessary. Do you agree with it? Also, is the rest of this PR needed once we implement that fix?

**Comment by ahnitz** [comment]
@titodalcanton Yes, that was definitely a bug

**Pull request merged**
