### PR TITLE
Coinc snrchi multiifo

### PR DESCRIPTION
**Pull request by spxiwh**
Re-enable the coinc_snrchi plots in the multiifo workflow. Doing this requires adding a small amount of code to the executable to handle both old- and new-format input.

### CODE REVIEW

**Comment by GarethDaviesGW** [comment]
Looks good in terms of converting for multiifo use and re-enabling in the workflow

In the example workflow you sent, the sg-chisq plots (e.g. [here](https://ligo.gravity.cf.ac.uk/~ian.harry/LVC/aLIGO/O3/HLV_testing/example_1/chunk1/run2d/5._injections/5.01_BNSSTT5_INJ/H1-PLOT_COINC_SNRCHI_SG_BNSSTT5_INJ_H1L1V1-1238165866-622112.png)) seem to all have reduced chi-squared = 1, is this expected?

**Comment by spxiwh** [comment]
The plot you point to is for BNS injections. The BNS waveforms are all going to be too short for sgchisq to be enabled. So I think we would expect all the injection triggers to have a value of 1 here. For the BBH injections there are a number of non-zero values.

**Comment by spxiwh** [comment]
There is some sub-optimality here, because we get one V1 plot for each of the coincident combinations. But I think having some of these plots is better than having none of these plots!

**Comment by GarethDaviesGW** [comment]
> There is some sub-optimality here, because we get one V1 plot for each of the coincident combinations. But I think having some of these plots is better than having none of these plots!

I think you may be able to change this line:
https://github.com/gwastro/pycbc/blob/master/pycbc/workflow/plotting.py#L185

to something which has only the ifos of the stat file (stat_file.ifo_list?) and make this change, but you're right, if it's not that easy it may be more trouble than it is worth

**Comment by GarethDaviesGW** [comment]
Would you be able to add which IFOs are used in the background into the title?

**Pull request merged**
