### PR TITLE
Remove old coincidence code

### LINKED ISSUE #2999: remember to revert temporary patch for legacy output in pycbc_coinc_findtrigs
Remember to revert #2997

### PR DESCRIPTION
**Pull request by spxiwh**
This PR removes all of the old coincidence code, and then renames the new code to swap it into place.

@GarethDaviesGW I have not edited codes that might have support *both* the old and new interfaces. If you have a list of which files that would be, I can rip out support for the old interface from those codes.

Because of the rename the diff here is confusing, but you can see from the individual commits that this is just a delete and then move.

Fixes #2999 (Look I didn't forget @ahnitz )

### CODE REVIEW

**Comment by GarethDaviesGW** [comment]
> @GarethDaviesGW I have not edited codes that might have support _both_ the old and new interfaces. If you have a list of which files that would be, I can rip out support for the old interface from those codes.

A brief look finds the following places which have support for the old interface (search for detector_1):
pycbc_foreground_minifollowup
pycbc_page_coincinfo
pycbc_page_coinc_snrchi
pycbc_page_injtable
pycbc_page_recovery

pycbc_multiifo_coinc_findtrigs has the --legacy-output flag

This might not be all of the places, and basically relied on git grepping keywords that i could think of

N.B. from what i remember most, if not all, of Josh's checks in workflow_comparisons are based on the old coinc code, so these will need updating

**Comment by spxiwh** [comment]
I think I've now removed the old coinc code ability from all the places listed (and hdfinjfind). I do need to test that though, and the diff here is already unreadable, so would prefer to merge this as is and then add that in a later PR.

**Review by GarethDaviesGW — APPROVED** [review]
When this is made into a tagged version, we'll need to have some significant changes to the executables.ini file before it will work

(This is just to get this written down as a reminder, as I'm sure you're aware of that)

**Review by ahnitz — COMMENTED** [review]
Wait, so the renaming here will likely break the public configs files, no? That test is offline at the moment, but I can work today to add it back in. I would prefer we have some set of config files that work for testing on master, not just tagged releases.

So I guess please hold off merging until I can add that test back in to make sure nothing breaks.

**Comment by spxiwh** [comment]
@ahnitz This will break config files. As we are staging #3535 as multiple commits I'm not doing large scale tests on anything other than the full #3535 stack (so I would advocate to not run the all-sky search on code while this is in the middle of being merged, and either use the last release, or wait for this to go in completely).

However, keeping the configs up-to-date will be useful .... The automated test will probably only catch changes in exe names, so maybe isn't testing all that much beyond the workflow generation, but I'm happy to keep that working. Is this covered in #3542?

**Comment by ahnitz** [comment]
@spxiwh That's fair. I'm OK for this to merge then. The workflow build test was actually part of the docker builds, which we don't currently have. I need to migrate that to the unified test suite. Now that I think of it, I don't remember which workflow it was testing, so I can probably update it myself for now. As you say, it should just be some executable names, so probably not too hard to keep working.

**Comment by tdent** [comment]
Same comment as on the plotting codes : "Can users please be given some general overview of any major reorganization of the code directory structure in the pycbc-code channel?" 

This will probably cause a lot of instances of 'what is that code now called and where can I find it' for me.

**Pull request merged**
