### PR TITLE
Consolidate resolve url

### PR DESCRIPTION
**Pull request by spxiwh**
So this carries on from #3360 with similar motivations (or at least playing around with #3360 lead to me needing to do this).

In short we use `resolve_url` to pull in inputs in a few cases, but this always needs extra commands after it to convert to a File object. I want to create a one-shot `resolve_url_to_file` function, that will return a File object with all necessary attributes/PFNs attached to it.

As an example, if an input is on CVMFS, and I want to run on OSG (let's say an injection file on CVMFS, or a template bank) the workflow generator will pull the file to the local site, and then it will be gsiftp-ed to the OSG sites in question. It would be better if the remote site can just get that via CVMFS (as happens with frame files, which are a bit of a special case, so not touched in this patch).

Trying to duplicate this kind of stuff after all `resolve_url` calls makes no sense, but with a new combined function, we can add PFNs for this. If something comes from CVMFS, we add it's cvmfs PFN to all sites (local, osg and the new nonfsio site). If others want default behaviours here for other sites, just add it to this function.

One open question: For the local site I would prefer it if the CVMFS location is preferred over other /file locations (assumed to be NFS mounts). However, if I swap this it's swapped for all users. What are the thoughts on that? (This probably wouldn't affect frame files, as we tend not to get both CVMFS *and* local PFNs in the standard route through the workflow).

### CODE REVIEW

**Comment by spxiwh** [comment]
I've dealt with most of the codeclimate stuff. The remaining items are not new and I'm not going to try and fix it in this patch.

**Comment by ahnitz** [comment]
@spxiwh some initial thoughts
I don't really mind about preferring CVMFS (but only because we aren't using it, so there'll be no conflict), but this may have effects for Duncan as I assume they'll also hit this when running on OSG. What this is really telling me is that we need to think a bit about how we communicate site information / preferences when we mock up peagsus 5 support (as that will be a good time to revisit some of these areas). Until that switch, I guess it's not worth moving away from hardcoding this kind of thing, but it would be nice to not have to in the future.

**Comment by spxiwh** [comment]
@ahnitz I certainly agree that we would want to revisit some of these kinds of things when we have pegasus5.

I think the changes to add cvmfs locations to the OSG site are what we want. We already assume OSG has cvmfs from frame files and special cases (like osgconnect, which I don't understand) I don't touch. The "prefer local vs cvmfs" change wouldn't affect OSG either, as I'm not really aware of any use cases where we give OSG PFNs that are not in CVMFS *and* OSG PFNs that are. (Files copied from the local site will always be disfavoured over something identified as being on the OSG site, regardless of path name) ... But I'm CCing Duncan into these PRs anyway ... And we can always continue to tweak this to support what works best over multiple sites/configurations.

**Comment by duncan-brown** [comment]
@spxiwh I'm not sure this is the right way to solve the problem that you have and I'm worried about the default to CVMGS. Am I right that the underlying issue is that you want the workflow to use an intermediate data product file from CVMS (template bank or injection file) rather than transfer it to the site?

Can you just add the path to that file to the workflow's file catalog? I may be misunderstanding what you're trying to do here.

**Comment by spxiwh** [comment]
@duncan-brown I think that's exactly what I'm doing here! With the current code on master, if an input file is on CVMFS, the CVMFS address is *not* added to the list of PFNs (and then to the list of file locations in the dax). This changes that.

I have not changed any defaults here, and to avoid further confusion, I will not consider any more points about defaulting, or not, to CVMFS locations where available.

The main changes here are just:

 * Avoid a bunch of code duplication around `resolve_url` in the workflow
 * Register the CVMFS locations when an input comes from CVMFS.

**Comment by spxiwh** [comment]
Maybe you are saying that we should not transfer a file to the local site if it is already on CVMFS? I think I agree with that, but there is no change here to the current behaviour where we *will* transfer a file to the local site if it is on CVMFS.

What I'm stopping is then transferring (by gsiftp) that file to OSG if it's on CVMFS!

**Comment by duncan-brown** [comment]
@spxiwh ok, thanks I think I understand. I had misunderstood @ahnitz's concern above, I think. I'm happy with this, but will add it to the list of things to check and see if we need to [fix things properly](https://www.youtube.com/watch?v=5N0ATdDdwKg) once Pegasus 5 is out.

**Pull request merged**
