### PR TITLE
updates to github pages

### PR DESCRIPTION
**Pull request by ahnitz**

### CODE REVIEW

**Comment by ahnitz** [comment]
@spxiwh Ok, this does a couple things. 

1) re-enable the pycbc live test (accidentally disabled since it required an environment flag I wasn't setting)
2) upload documentation when a change to master is made (requires tests to also pass, also docs are uploaded as artefact in all builds so one can see them in your tests report for any PR now). 
3) make releases to pypi and test-pypi, pypi only on tagged release (same as before with travis) and test-pypi on every commit to master. 

I couldn't fully vet the release procedure without doing an actual release, but I did test that the testpypi uploads are made in a sane way. It's the same procedure, so fingers crossed that it fully works.

**Comment by spxiwh** [comment]
One quick question here. (Probably not related to this PR per say, but the new testing stuff). Why are all of the tests run twice? (One for `push` and one for `pull_request`) ... Do we need both to be run? 42 tests is starting to seem like a lot! (It's about 7 hours of CPU time for every push).

**Review by spxiwh — APPROVED** [review]
I don't understand github actions yet, but this seems to do what you say (more tests are running with ticks), and it doesn't touch the main repo stuff, so I'll just take your word that this all makes sense :-)

**Comment by ahnitz** [comment]
@spxiwh In this case, I think it was done since I was also testing this on a branch at gwastro. I needed to do that to make sure the credentials worked for pushing to the repo (i.e. for the documentation), as those only work when the source branch is the main repo itself (for obvious security implications). Github seems to have recognized the branches were identical and shown both results here.

**Pull request merged**
