### PR TITLE
enable basic mac tests

### PR DESCRIPTION
**Pull request by ahnitz**

### CODE REVIEW

**Comment by ahnitz** [comment]
Depends on #3632 and #3629

**Comment by ahnitz** [comment]
Putting this on hold until a bunch of prereqs in other PRs are merged.

**Comment by ahnitz** [comment]
@spxiwh I found one really weird thing here. "TaylorT2" is return NaNs but only in python3.8 in the mac environment. This was causing the autochisq test to fail. Switching to SpinTaylorT4 and adjusting the test allows it to pass. However, I'm somewhat uncomfortable with this. 

@spxiwh The github env is supposed to be mac os 10.15. Do you know if TaylorT2 works for you in a 3.8 env and that OS?

**Review by spxiwh — APPROVED** [review]
Thanks! This looks good. At the moment I don't have this OS, or this version of python3 installed on my mac, so won't be able to test this immediately. So approving now anyway.

SpinTaylorT5 is more used anyway ... But it doesn't really make sense why p37 -> p38 would cause differences in *one* lalsim approximant on a mac. (I might suspect something beyond just python changes)

**Comment by ahnitz** [comment]
@spxiwh Yes, I agree. I suspect that lalsuite is either picking up (or has bundled with it) a different system library there which is failing.

**Pull request merged**
