### PR TITLE
Fixes to allow workflows to be run on OrangeGrid

### PR DESCRIPTION
**Pull request by duncan-brown**

### CODE REVIEW

**Comment by duncan-brown** [comment]
@spxiwh will fix the code climate things, but I'm loath to write new modules to handle this as it should really be handled at the datafind server level. PyCBC should not have any hard-coded paths at all, as that is admin-level knowlege. You should be able to query the datafind server for a specific site to find out what files are available on that site and what the paths are. I've raised this with Stuart and Tom a couple of times, but I don't know what the long-term future of datafind is within the LSC.

**Comment by spxiwh** [comment]
Okay. I'm not aware of any thoughts about retiring datafind any time soon, but you're right that it's not great having all these hardcoded paths here. A few thoughts:

 * There's no reason why `datafind.py` cannot query multiple and/or external datafind servers.
 * I guess on the LVC side we need a way of figuring out how to get OSG locations instead of adding paths manually.
 * I guess on your side you want GWOSC data in both CVMFS and directly from the GWOSC server. Isn't there a better way of getting the latter?

**Comment by duncan-brown** [comment]
@spxiwh datafind.py can query multiple servers, but unless those servers have some knowledge of "site", pycbc needs hard-coded logic somewhere. For example, suppose I set up a server that indexes GWOSC data in /cvmfs. I'd have to set up a *second* server that indexes GWOSC data from https://gw-astronomy.org/ So you'd need one datafind server per site, which doesn't really scale.

**Comment by duncan-brown** [comment]
For some reason travis has lost track of this PR. Closing and re-opening.

**Pull request closed without merging**
