### PR TITLE
More detailed description for GRB sky error func

### PR DESCRIPTION
**Pull request by a-r-williamson**
Also included a new argument to allow for different probability
coverage. Default is the same as old hardcoded value of 90%.

### CODE REVIEW

**Comment by a-r-williamson** [comment]
Tessa Carver is checking whether the Fermi-GBM systematic value is relevant for O3A GRBs. Will wait for confirmation or correction before merging.

**Comment by pannarale** [comment]
@a-r-williamson, could you fix the last 2 codclimate issues, please?  That's: line too long, and blank line at EOF.

**Comment by pannarale** [comment]
Hi @tcarver1234, your latest commits introduced some codeclimate issues (whitespaces and indentations mainly).  Please fix as many as you can.

Then there is a conflict to be resolved (tagging @a-r-williamson too).

**Comment by a-r-williamson** [comment]
@tcarver1234 You removed the precision argument but the variable is still used in the function. Did you mean to change the function as well in some way?

**Comment by a-r-williamson** [comment]
This function is not being called in master.
https://github.com/gwastro/pycbc/blob/3f6c49a2802d9f13cdac9f18582d2dd7537b0689/pycbc/workflow/matched_filter.py#L303-L319
It looks like `master` has thrown the `coh_PTF` interface away. Is this function still needed, and if so is this the correct place for it?

**Comment by ahnitz** [comment]
@a-r-williamson What is the status of this? Is this PR still active?

**Review by pannarale — APPROVED** [review]
We should push this small change to master before it lags behind other development or is coded up again.

[We will be forced to revisit this whole file further down the line in any case, once when we start using it again, e.g., some parts will not work with Pegasus5.]

**Pull request merged**
