### PR TITLE
Switch PyCBC to using keytabs

### PR DESCRIPTION
**Pull request by ahnitz**
I need to test this from a branch on the gwastro repo to allow the secure key required portions to run.

### CODE REVIEW

**Comment by duncan-brown** [comment]
@ahnitz is this still relevant?

**Comment by ahnitz** [comment]
Should leave it for now, or remove our testing that requires ligo.org access and do that some other way.

**Comment by duncan-brown** [comment]
@ahnitz I think we need to resurrect this as `ligo-proxy-init` seems to have changed and it looks like Travis is failing when it tries to apply the patch.

**Comment by ahnitz** [comment]
obsoleted

**Pull request closed without merging**
