### PR TITLE
copy over more comprehensive search/livetime info

### PR DESCRIPTION
**Pull request by tdent**

### CODE REVIEW

**Comment by tdent** [comment]
OK. I tried to test this with your files at /home/gdavies/analyses/pycbc/multiifodev/test_multiifo_coinc_rate_statistic/output/ but I think some of those will have needed to be hacked as e.g. the injection statmap files did not have the `ifos` attribute yet.

**Comment by tdent** [comment]
in any case the current statmap_inj code tells me that the foreground time(_exc) and ifos attributes will be present.

**Comment by GarethDaviesGW** [comment]
There are some STATMAP_INJ files in `/home/gdavies/test_codes/pycbc/statmap_inj_multiifo_testing/data_files/` which I made when testing the statmap_inj changes which are up-to-date

**Comment by tdent** [comment]
actually the V1H1L1- MULTIIFO_STATMAP_INJ_BBHSEOBNRV4_INJ_INJECTIONS_3DET_H1L1V1_CUMULATIVE_CAT_12H-1238166018-853200.hdf file doesn't have an `ifos` attribute for whatever reason.

**Pull request merged**
