### PR TITLE
edit example seach config to enanble decimation again

### PR DESCRIPTION
**Pull request by ahnitz**

### CODE REVIEW

**Comment by titodalcanton** [comment]
So this is the fix for the thing that was causing the small search to fail, right? I think it is best if @GarethCabournDavies can double check the updated config here.

**Comment by ahnitz** [comment]
@titodalcanton Yes, it failed because the settings were incorrectly labelled so it turned off any decimation. That caused the coinc job memory useage to balloon far beyond the memory limit of the machine, hence all jobs slowed to a crawl as they probably were stuck swapping to disk.

**Comment by GarethCabournDavies** [comment]
This seems good for the small search config change, but we will still need to fix the issue as a whole

**Review by GarethCabournDavies — APPROVED** [review]

**Comment by ahnitz** [comment]
@GarethCabournDavies Yeah, agree. It's a problem that we can't use negative values.

**Pull request merged**
