### PR TITLE
add p39 to testing

### PR DESCRIPTION
**Pull request by ahnitz**

### CODE REVIEW

**Comment by spxiwh** [comment]
Inference doesn't seem to like python 3.9 :-(

**Comment by ahnitz** [comment]
@spxiwh @cdcapano Looks to me like maybe a p39 issue with just the epsie sampler

**Comment by ahnitz** [comment]
Putting on hold. May need a new release of epsie (to avoid having to drop it in the test)

**Comment by ahnitz** [comment]
@cdcapano I've tracked the issue down to the randomgen depenency that epsie has. It does not run in python3.9 and the latest numpy environments. 

```
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-3-cb52c5294316> in <module>
----> 1 import pycbc.inference.sampler.epsie

~/projects/env39/lib/python3.9/site-packages/PyCBC-0.0a8103-py3.9-linux-x86_64.egg/pycbc/inference/sampler/epsie.py in <module>
     21 import numpy
     22 
---> 23 import epsie
     24 from epsie.samplers import ParallelTemperedSampler
     25 

~/projects/env39/lib/python3.9/site-packages/epsie/__init__.py in <module>
     28 from io import BytesIO
     29 import numpy
---> 30 from randomgen import PCG64
     31 
     32 #

~/projects/env39/lib/python3.9/site-packages/randomgen/__init__.py in <module>
      2 import sys
      3 
----> 4 from randomgen.aes import AESCounter
      5 from randomgen.chacha import ChaCha
      6 from randomgen.dsfmt import DSFMT

~/projects/env39/lib/python3.9/site-packages/randomgen/aes.pyx in init randomgen.aes()

~/projects/env39/lib/python3.9/site-packages/randomgen/common.pyx in init randomgen.common()

__init__.pxd in numpy.import_array()

ImportError: numpy.core.multiarray failed to import
```

**Comment by ahnitz** [comment]
@cdcapano This can be reproduced by simply doing 
```
pip install numpy==1.19.5 randomgen
```
Then try to import randomgen

**Comment by ahnitz** [comment]
@cdcapano I think this is a problem with randomgen and python 3.9. It doesn't yet have a wheel for python3.9 and the default tar package doesn't seem to be compatible in this case. This might be resolved for our personal testing purposes after #3646, but will likely remain flakey untill they have a python3.9 release.

**Comment by cdcapano** [comment]
@ahnitz Sorry about that. Yeah, randomgen will not have a 3.9 release, since it was worked into numpy as of version 1.17. I've actually dropped randomgen (along with py27 support) and switched entirely to numpy on the master of epsie, but haven't created a release yet as I wanted to fix a few other issues first. How much of time pressure is this? I can get back to updating epsie the second half of next week, and create a new release then. Is that ok?

In the CI tests on epsie's master, I'm testing in python 3.6 - 3.9 environments, so it definitely should be ok in 3.9 once I make the release.

**Comment by ahnitz** [comment]
@cdcapano No time pressure at all.

**Comment by ahnitz** [comment]
@spxiwh @cdcapano Unpinning numpy did in fact work to get the tests working in 3.9, so I think we can merge this now.

**Review by spxiwh — APPROVED** [review]

**Pull request merged**
