### PR TITLE
Add method to convert a section into command-line string

### PR DESCRIPTION
**Pull request by cdcapano**
This adds a class method to `WorkflowConfigParser` that will convert all of the options in a given section into a command-line-like string of options. (The string can then be passed to an argument parser.) See the example in the doc string.

Needed by #2803.

### CODE REVIEW

**Comment by spxiwh** [comment]
Can you comment on why this is needed in the first place? Why are these options not being given to the job directly on the command line?

**Comment by cdcapano** [comment]
@spxiwh It's not for a workflow. I'm working on moving the data options for `pycbc_inference` from the command line to its config file. (See #2803) I'd still like to use all of the from cli utilities in the strain module though, so the easiest way to do this is just convert the section options into a string that can be read by `ArgumentParser.parse_args`. See [here](https://github.com/gwastro/pycbc/blob/025360a67ae63553f072cf4d2b9018b2a909b76c/pycbc/inference/models/gaussian_noise.py#L723-L791), which is called [here](https://github.com/gwastro/pycbc/blob/025360a67ae63553f072cf4d2b9018b2a909b76c/pycbc/inference/models/gaussian_noise.py#L631-L632), for how I'm planning to use this.

**Comment by spxiwh** [comment]
Okay ... For running in a workflow it might be messy to have the workflow setup config file, and the inference running options config file, which should really be two separate things.

Would it make sense to be able to provide options in a config file (for running inference on its own) *or* to provide options on the command line (for running inference in a workflow)?

**Comment by cdcapano** [comment]
@spxiwh Thanks for approving. Let's move this discussion about what to do with the options in the workflow over to #2308.

**Pull request merged**
