### PR TITLE
PyCBC Live: fix SNR series error for triggers straggling the chunk boundary

### LINKED ISSUE #2249: Sporadic error in SNR series generation in PyCBC Live
Reported by @ahnitz:
```
2018-07-07 10:26:10,410 atlas4 done clustering coinc triggers: 1478 triggers remaining
2018-07-07 10:26:10,471 atlas4 Generating SPAtmplt, 80.0s, 341678, starting from 26.9 Hz
Traceback (most recent call last):
File "/home/pycbc.live/projects/pycbc_live_production/O3exp/env/bin/pycbc_live", line 4, in <module>
__import__('pkg_resources').run_script('PyCBC===48da87', 'pycbc_live')
File "/home/pycbc.live/projects/pycbc_live_production/O3exp/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 654, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/home/pycbc.live/projects/pycbc_live_production/O3exp/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1434, in run_script
exec(code, namespace, namespace)
File "/home/pycbc.live/projects/pycbc_live_production/O3exp/env/lib/python2.7/site-packages/PyCBC-48da87-py2.7-linux-x86_64.egg/EGG-INFO/scripts/pycbc_live", line 515, in <module>
followup_ifos=usable_followup_ifos)
File "/home/pycbc.live/projects/pycbc_live_production/O3exp/env/lib/python2.7/site-packages/PyCBC-48da87-py2.7-linux-x86_64.egg/EGG-INFO/scripts/pycbc_live", line 114, in check_coincs
bank, followup_ifos)
File "/home/pycbc.live/projects/pycbc_live_production/O3exp/env/lib/python2.7/site-packages/PyCBC-48da87-py2.7-linux-x86_64.egg/EGG-INFO/scripts/pycbc_live", line 103, in compute_followup_data
check_state=(ifo in followup_ifos))
File "/home/pycbc.live/projects/pycbc_live_production/O3exp/env/lib/python2.7/site-packages/PyCBC-48da87-py2.7-linux-x86_64.egg/pycbc/filter/matchedfilter.py", line 1782, in compute_followup_snr_series
return snr[onsource_slice] * norm, stilde.psd
File "<decorator-gen-120>", line 2, in __getitem__
File "/home/pycbc.live/projects/pycbc_live_production/O3exp/env/lib/python2.7/site-packages/PyCBC-48da87-py2.7-linux-x86_64.egg/pycbc/types/array.py", line 65, in _convert
return fn(self, *args)
File "/home/pycbc.live/projects/pycbc_live_production/O3exp/env/lib/python2.7/site-packages/PyCBC-48da87-py2.7-linux-x86_64.egg/pycbc/types/array.py", line 738, in __getitem__
return self._getslice(index)
File "/home/pycbc.live/projects/pycbc_live_production/O3exp/env/lib/python2.7/site-packages/PyCBC-48da87-py2.7-linux-x86_64.egg/pycbc/types/timeseries.py", line 105, in _getslice
raise ValueError('Negative start index not supported')
ValueError: Negative start index not supported
```

### PR DESCRIPTION
**Pull request by titodalcanton**
Fixes #2249 and further simplifies and documents the GraceDB/BAYESTAR interface.

Testing.

### CODE REVIEW

**Comment by ahnitz** [comment]
@titodalcanton Yeah, that seems unrelated. By any chance can you check what numpy version you were running in that environment? I wonder if it is a new version that may have changed the behavior of the resize method.

**Comment by titodalcanton** [comment]
That is on numpy 1.13.1.

**Comment by ahnitz** [comment]
Oh... so *not* a new one.

**Comment by ahnitz** [comment]
Well, I don't have any immediate ideas.

**Comment by ahnitz** [comment]
@titodalcanton Are you still seeing this resize issue? Is there anything else?

**Comment by titodalcanton** [comment]
I have not tested this in a while. I guess you did not see this error on your most recent tests at CIT right? If so I think we can close this, and I can open a new issue if I see it again.

**Pull request merged**
