### PR TITLE
Remove einsteinathome folder

### PR DESCRIPTION
**Pull request by GarethCabournDavies**
Remove unmaintained, unused folder

### CODE REVIEW

**Comment by ahnitz** [comment]
@GarethCabournDavies We can probably remove the einsteinathome folder. It's unmaintained at this point and I think unlikely to come back.

**Comment by GarethCabournDavies** [comment]
Is the build script (pycbc_build_eah.sh, described at https://pycbc.org/pycbc/latest/html/building_bundled_executables.html) still used for building bundled executables for use on the OSG?

**Comment by spxiwh** [comment]
We don't bundle in the old way used here. Singularity images now produce the functionality of being able to run on other clusters without having to explicitly install code there.

**Review by ahnitz — APPROVED** [review]
This looks good to me! Thanks for the cleanup

**Pull request merged**
