### PR TITLE
Added ability to accept multiple frame files to pycbc_make_skymap.

### PR DESCRIPTION
**Pull request by MarlinSchaefer**
For certain purposes it might be useful to process multiple custom frames when using pycbc_make_skymap. I therefore added the ability for the code to handle a list of multiple frames per interferometer.

### CODE REVIEW

**Comment by ahnitz** [comment]
@MarlinSchaefer Were you able to test this by running by hand?

**Comment by MarlinSchaefer** [comment]
@ahnitz I used it on a previous test case (just single file per detector) and it ran without issues. I haven't run a test with multiple files as I didn't have one handy. Will do so and add a comment once that is done.

**Comment by MarlinSchaefer** [comment]
@ahnitz I now checked it for multiple files and there actually was an issue with checking the segment. I adjusted the issue (quite naively, buy just assuming the given files span a continuous stretch) and now the code fails at the stage where pycbc_single_template is called. It gives the error `OSError: /tmp/tmpgogm0q9d/PSD_271_H1.txt not found.`. The stderr-file gives:
```python
2020-08-14 14:03:53,456 Running with CPU support: 1 threads
2020-08-14 14:03:53,456 Reading Frames
XLAL Error - XLALFrStreamFileOpen (LALFrStream.c:128): No files in stream file cache
XLAL Error - XLALFrStreamFileOpen (LALFrStream.c:128): Invalid argument
XLAL Error - XLALFrStreamCacheOpen (LALFrStream.c:233): Internal function call failed: Invalid argument
Traceback (most recent call last):
  File "/home/marlin/environments/pycbc_issues/bin/pycbc_single_template", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/marlin/environments/pycbc_issues/src/pycbc/bin/pycbc_single_template", line 216, in <module>
    gwstrain = strain.from_cli(opt, pycbc.DYN_RANGE_FAC)
  File "/home/marlin/environments/pycbc_issues/src/pycbc/pycbc/strain/strain.py", line 231, in from_cli
    sieve=sieve)
  File "/home/marlin/environments/pycbc_issues/src/pycbc/pycbc/frame/frame.py", line 202, in read_frame
    stream = lalframe.FrStreamCacheOpen(cum_cache)
RuntimeError: Internal function call failed: Invalid argument
```
I'm not sure what I can get from that error.

**Comment by MarlinSchaefer** [comment]
Tracked down the error to be caused by not properly passing the custom frame-files to pycbc_make_skymap. Afterwards discovered that the sample-rate for the data was hard coded to be 2048. Changed the sample-rate to be an option with default value 2048.

**Pull request merged**
