### PR TITLE
do not hard require old emcee version, do require lalsuite

### PR DESCRIPTION
**Pull request by ahnitz**
This removes the hard requirement in pycbc inference on emcee 2. It's left in the requirements file for a standard environment, but no longer in setup.py which would make it impossible to make your own environment without emcee2.

### CODE REVIEW

**Comment by ahnitz** [comment]
Note to self: This means that when it is included in a release, the tutorials will need to be updated to include emcee for the ones that require this.

**Comment by ahnitz** [comment]
@spxiwh While trying to clean up dependencies, I've added the lalsuite package in. Is this OK for the LSC uses?

**Comment by ahnitz** [comment]
@spxiwh Obviously I would like to make lalsuite optional, but in practice it is not at the moment hence the current setup.py is not quite correct.

**Comment by spxiwh** [comment]
@ahnitz I leave this for Collin to review formally, but adding lalsuite in setup.py doesn't add any complications for "production" LVC stuff. I think there's a common PyCBC use-case where someone installs a custom lalsuite from source and uses PyCBC to test/evaluate some new waveform. I don't think this complicates that.

**Review by cdcapano — APPROVED** [review]

**Pull request merged**
