### PR TITLE
Recover from https://git.ligo.org/lscsoft/lalsuite/-/merge_requests/1909

### PR DESCRIPTION
**Pull request by tdent**
FrSetMode was removed from lalframe, FrStreamSetMode seems to be equivalent

See https://git.ligo.org/lscsoft/lalsuite/-/merge_requests/1918/diffs

### CODE REVIEW

**Review by titodalcanton — APPROVED** [review]
Seems appropriate. Is there any other invocation of similar lalframe deprecated functions in PyCBC?

**Comment by tdent** [comment]
> Seems appropriate. Is there any other invocation of similar lalframe deprecated functions in PyCBC?

Git grep says no. Not sure what the failing tests are atm.

**Comment by tdent** [comment]
(to be clear, this function was removed, not deprecated, and I don't know if there is any way for us to know if a LAL function is considered to be 'deprecated')

**Comment by titodalcanton** [comment]
Failures appear to be due to errors in downloading input data at the moment.

**Pull request merged**
