### PR TITLE
Remove the gating file module

### PR DESCRIPTION
**Pull request by spxiwh**
This patch reverts #1865 and solves the issue reported there by adding `resolve_url` when processing input-file options in the workflow.core module.

So basically if you supply a phase-time consistency file, or a gating file, as a URL. The workflow will pull that file to the local directory when creating the dax file and then the dax file will reference the local URL.

This means that the entire gating module can again be removed from the workflow. Now instead of calling this just supply the gating options directly (like the channel-name options). So basically you would move the gating files to:

```
[workflow]
gating-file-h1 = https://git.ligo.org/SOME/PATH/TO/H1-GATES.txt
gating-file-l1 = https://git.ligo.org/SOME/PATH/TO/L1-GATES.txt
```

and then add this to all programs that need it. I think the current list is:

```
[inspiral-h1]
; Hanford specific matched-filter parameters
channel-name = ${workflow|h1-channel-name}
gating-file = ${workflow|gating-file-h1}

[inspiral-l1]
; Livingston specific matched-filter parameters
channel-name = ${workflow|l1-channel-name}
gating-file = ${workflow|gating-file-l1}

[calculate_psd-h1]
channel-name = ${workflow|h1-channel-name}
gating-file = ${workflow|gating-file-h1}

[calculate_psd-l1]
channel-name = ${workflow|l1-channel-name}
gating-file = ${workflow|gating-file-l1}

[single_template-h1&plot_singles_timefreq-h1&plot_qscan-h1]
frame-type = ${workflow-datafind|datafind-h1-frame-type}
channel-name = ${workflow|h1-channel-name}
gating-file = ${workflow|gating-file-h1}

[single_template-l1&plot_singles_timefreq-l1&plot_qscan-l1]
frame-type = ${workflow-datafind|datafind-l1-frame-type}
channel-name = ${workflow|l1-channel-name}
gating-file = ${workflow|gating-file-l1}
```

(I'm not actually sure if you want this in the qscan jobs or not ... Maybe you want to see the gated glitch, maybe not).

Anyway, this will require config file changes (otherwise the gating files are unused). I'll coordinate this on the LVC side. @tapaimarton pinging you as you would need to edit your developmental config files for this. Note the change to the new offline 3-detector workflow generator also.

### CODE REVIEW

**Comment by ahnitz** [comment]
@spxiwh Poke, this might require rebasing. @duncan-brown Any hold up in reviewing?

**Comment by spxiwh** [comment]
@duncan-brown Any comments? I'll assign this to @ahnitz if I don't hear anything.

**Comment by ahnitz** [comment]
@spxiwh One of the travis things looked like a timeout so I restarted it. If travis passes, I'll merge this.

**Comment by ahnitz** [comment]
@spxiwh We should merger this. Can you rebase?

**Comment by spxiwh** [comment]
This rebased cleanly, updated here now.

**Pull request merged**
