### PR TITLE
move multiifo workflow to use new segment interface

### PR DESCRIPTION
**Pull request by ahnitz**

### CODE REVIEW

**Comment by ahnitz** [comment]
Ok, my test gets this output. 
```
2019-06-03 16:28:04,319:INFO : Overriding section results_page option output-path with value ../../../html in configuration.
2019-06-03 16:28:04,362:INFO : Overriding section results_page option output-path with value ../../../html in configuration.
2019-06-03 16:28:04,402:INFO : Overriding section results_page option output-path with value ../../../html in configuration.
2019-06-03 16:28:04,429:INFO : Created log file /home/ahnitz/projects/fall/test/output/results/8._workflow/H1L1V1-WORKFLOW-LOG-1186624818-687900.txt
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/H1_DATA/1186624818/687900/
|======================================================================================================| 565 /565  (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/H1_DATA/1186624818/687900/
|======================================================================================================| 565 /565  (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/H1_CBC_CAT1/1186624818/687900/
|======================================================================================================| 569 /569  (100.00%)         0s
2019-06-03 16:28:06,842:INFO : H1: got segments-science flags
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/L1_DATA/1186624818/687900/
|======================================================================================================| 903 /903  (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/L1_DATA/1186624818/687900/
|======================================================================================================| 903 /903  (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/L1_CBC_CAT1/1186624818/687900/
|======================================================================================================| 907 /907  (100.00%)         0s
2019-06-03 16:28:09,117:INFO : L1: got segments-science flags
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/V1_DATA/1186624818/687900/
|======================================================================================================| 799 /799  (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/V1_DATA/1186624818/687900/
|======================================================================================================| 799 /799  (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/V1_CBC_CAT1/1186624818/687900/
|======================================================================================================| 803 /803  (100.00%)         0s
2019-06-03 16:28:11,816:INFO : V1: got segments-science flags
2019-06-03 16:28:11,852:INFO : Entering datafind module
no_test
SUMMARY CHECK
2019-06-03 16:28:11,852:INFO : Starting datafind with setup_datafind_runtime_generated
2019-06-03 16:28:11,852:INFO : Setting up connection to datafind server.
2019-06-03 16:28:11,852:INFO : Querying datafind server for all science segments.
2019-06-03 16:28:12,310:INFO : setup_datafind_runtime_generated completed
2019-06-03 16:28:12,328:INFO : Leaving datafind module
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/H1_DATA/1186624818/687900/
|======================================================================================================| 565 /565  (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/H1_CBC_CAT2/1186624818/687900/
|======================================================================================================| 1.8k/1.8k (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/H1_DATA/1186624818/687900/
|======================================================================================================| 565 /565  (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/H1_NO_CBC_HW_INJ/1186624818/687900/
|======================================================================================================| 132 /132  (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/H1_DATA/1186624818/687900/
|======================================================================================================| 565 /565  (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/H1_NO_BURST_HW_INJ/1186624818/687900/
|======================================================================================================| 134 /134  (100.00%)         0s
2019-06-03 16:28:16,741:INFO : H1: got segments-vetoes flags
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/L1_DATA/1186624818/687900/
|======================================================================================================| 903 /903  (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/L1_CBC_CAT2/1186624818/687900/
|======================================================================================================| 1.8k/1.8k (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/L1_DATA/1186624818/687900/
|======================================================================================================| 903 /903  (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/L1_NO_CBC_HW_INJ/1186624818/687900/
|======================================================================================================| 132 /132  (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/L1_DATA/1186624818/687900/
|======================================================================================================| 903 /903  (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/L1_NO_BURST_HW_INJ/1186624818/687900/
|======================================================================================================| 134 /134  (100.00%)         0s
2019-06-03 16:28:21,183:INFO : L1: got segments-vetoes flags
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/V1_DATA/1186624818/687900/
|======================================================================================================| 799 /799  (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/V1_CBC_CAT2/1186624818/687900/
|======================================================================================================| 803 /803  (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/V1_DATA/1186624818/687900/
|======================================================================================================| 799 /799  (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/V1_NO_CBC_HW_INJ/1186624818/687900/
|======================================================================================================| 132 /132  (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/V1_DATA/1186624818/687900/
|======================================================================================================| 799 /799  (100.00%)         0s
Downloading https://www.gw-openscience.org/timeline/segments/json/O2_16KHZ_R1/V1_NO_BURST_HW_INJ/1186624818/687900/
|======================================================================================================| 134 /134  (100.00%)         0s
2019-06-03 16:28:25,550:INFO : V1: got segments-vetoes flags
2019-06-03 16:28:25,564:INFO : Entering static psd module.
2019-06-03 16:28:25,565:INFO : Entering template bank generation module.
2019-06-03 16:28:25,565:INFO : Setting template bank from pre-generated bank(s).
2019-06-03 16:28:25,568:INFO : Starting new HTTPS connection (1): raw.github.com
2019-06-03 16:28:25,718:INFO : Starting new HTTPS connection (1): raw.githubusercontent.com
2019-06-03 16:28:26,064:INFO : Input bank is a xml.gz file
2019-06-03 16:28:26,065:INFO : convert template bank to HDF
2019-06-03 16:28:26,072:INFO : Leaving template bank generation module.
2019-06-03 16:28:26,072:INFO : Entering split output files module.
2019-06-03 16:28:26,072:INFO : Adding split output file jobs to workflow.
2019-06-03 16:28:26,083:INFO : Leaving split output files module.
2019-06-03 16:28:26,091:INFO : Entering matched-filtering setup module.
2019-06-03 16:28:26,091:INFO : Adding matched-filter jobs to workflow.
2019-06-03 16:28:26,091:INFO : Setting up matched-filtering for V1.
2019-06-03 16:28:28,956:INFO : Setting up matched-filtering for H1.
2019-06-03 16:28:31,373:INFO : Setting up matched-filtering for L1.
2019-06-03 16:28:33,735:INFO : Leaving matched-filtering setup module.
2019-06-03 16:28:40,320:INFO : Setting up coincidence
2019-06-03 16:28:40,427:INFO : ...leaving coincidence 
2019-06-03 16:28:40,428:INFO : Setting up coincidence
2019-06-03 16:28:40,509:INFO : ...leaving coincidence 
2019-06-03 16:28:40,510:INFO : Setting up coincidence
2019-06-03 16:28:40,588:INFO : ...leaving coincidence 
2019-06-03 16:28:40,588:INFO : Setting up coincidence
2019-06-03 16:28:40,797:INFO : ...leaving coincidence 
2019-06-03 16:28:40,797:INFO : Setting up multiifo combine statmap
2019-06-03 16:28:44,319:INFO : Entering minifollowups module
2019-06-03 16:28:44,364:INFO : Leaving minifollowups module
2019-06-03 16:28:44,365:INFO : Entering minifollowups module
2019-06-03 16:28:44,416:INFO : Leaving minifollowups module
2019-06-03 16:28:44,417:INFO : Entering minifollowups module
2019-06-03 16:28:44,480:INFO : Leaving minifollowups module
2019-06-03 16:28:44,481:INFO : Entering minifollowups module
2019-06-03 16:28:44,540:INFO : Leaving minifollowups module
2019-06-03 16:28:44,541:INFO : Entering minifollowups module
2019-06-03 16:28:44,596:INFO : Leaving minifollowups module
2019-06-03 16:28:44,596:INFO : Entering minifollowups module
2019-06-03 16:28:44,644:INFO : Leaving minifollowups module
2019-06-03 16:28:44,644:INFO : Entering minifollowups module
2019-06-03 16:28:44,686:INFO : Leaving minifollowups module
2019-06-03 16:28:44,687:INFO : Entering minifollowups module
2019-06-03 16:28:44,739:INFO : Leaving minifollowups module
2019-06-03 16:28:44,739:INFO : Entering minifollowups module
2019-06-03 16:28:44,786:INFO : Leaving minifollowups module
2019-06-03 16:28:44,786:INFO : Entering minifollowups module
2019-06-03 16:28:44,827:INFO : Leaving minifollowups module
2019-06-03 16:28:44,828:INFO : Entering minifollowups module
2019-06-03 16:28:44,867:INFO : Leaving minifollowups module
2019-06-03 16:28:44,867:INFO : Entering minifollowups module
2019-06-03 16:28:44,925:INFO : Leaving minifollowups module
2019-06-03 16:28:44,925:INFO : Entering minifollowups module
2019-06-03 16:28:44,967:INFO : Leaving minifollowups module
2019-06-03 16:28:56,981:INFO : Entering split output files module.
2019-06-03 16:28:56,981:INFO : Adding split output file jobs to workflow.
2019-06-03 16:28:57,044:INFO : Leaving split output files module.
2019-06-03 16:28:57,044:INFO : Entering injection module.
2019-06-03 16:28:57,138:INFO : Leaving injection module.
2019-06-03 16:28:57,229:INFO : Entering matched-filtering setup module.
2019-06-03 16:28:57,237:INFO : Adding matched-filter jobs to workflow.
2019-06-03 16:28:57,238:INFO : Setting up matched-filtering for V1.
2019-06-03 16:28:57,962:INFO : Setting up matched-filtering for H1.
2019-06-03 16:28:59,169:INFO : Setting up matched-filtering for L1.
2019-06-03 16:28:59,785:INFO : Leaving matched-filtering setup module.
2019-06-03 16:29:00,349:INFO : Setting up coincidence for injections
2019-06-03 16:29:00,499:INFO : ...leaving coincidence for injections
2019-06-03 16:29:00,516:WARNING : warning: config file is missing section [multiifo_statmap_inj]
2019-06-03 16:29:00,555:INFO : Setting up coincidence for injections
2019-06-03 16:29:00,692:INFO : ...leaving coincidence for injections
2019-06-03 16:29:00,709:WARNING : warning: config file is missing section [multiifo_statmap_inj]
2019-06-03 16:29:00,745:INFO : Setting up coincidence for injections
2019-06-03 16:29:00,888:INFO : ...leaving coincidence for injections
2019-06-03 16:29:00,905:WARNING : warning: config file is missing section [multiifo_statmap_inj]
2019-06-03 16:29:00,944:INFO : Setting up coincidence for injections
2019-06-03 16:29:01,451:INFO : ...leaving coincidence for injections
2019-06-03 16:29:01,591:WARNING : warning: config file is missing section [multiifo_statmap_inj]
2019-06-03 16:29:01,634:INFO : Setting up multiifo combine statmap
2019-06-03 16:29:01,797:INFO : Entering matched-filtering setup module.
2019-06-03 16:29:01,798:INFO : Adding matched-filter jobs to workflow.
2019-06-03 16:29:01,798:INFO : Setting up matched-filtering for V1.
2019-06-03 16:29:02,648:INFO : Setting up matched-filtering for H1.
2019-06-03 16:29:03,247:INFO : Setting up matched-filtering for L1.
2019-06-03 16:29:04,575:INFO : Leaving matched-filtering setup module.
2019-06-03 16:29:05,111:INFO : Setting up coincidence for injections
2019-06-03 16:29:05,269:INFO : ...leaving coincidence for injections
2019-06-03 16:29:05,287:WARNING : warning: config file is missing section [multiifo_statmap_inj]
2019-06-03 16:29:05,327:INFO : Setting up coincidence for injections
2019-06-03 16:29:05,482:INFO : ...leaving coincidence for injections
2019-06-03 16:29:05,499:WARNING : warning: config file is missing section [multiifo_statmap_inj]
2019-06-03 16:29:05,541:INFO : Setting up coincidence for injections
2019-06-03 16:29:05,695:INFO : ...leaving coincidence for injections
2019-06-03 16:29:05,712:WARNING : warning: config file is missing section [multiifo_statmap_inj]
2019-06-03 16:29:05,753:INFO : Setting up coincidence for injections
2019-06-03 16:29:06,264:INFO : ...leaving coincidence for injections
2019-06-03 16:29:06,405:WARNING : warning: config file is missing section [multiifo_statmap_inj]
2019-06-03 16:29:06,450:INFO : Setting up multiifo combine statmap
2019-06-03 16:29:49,036:INFO : Written dax.
```

**Comment by ahnitz** [comment]
I used this data configuration for my test. 
```
[workflow]
; http://ligo-cbc.github.io/pycbc/releases/v1.2.0/html/workflow/initialization.html
h1-channel-name = H1:GWOSC-16KHZ_R1_STRAIN
l1-channel-name = L1:GWOSC-16KHZ_R1_STRAIN
v1-channel-name = V1:GWOSC-16KHZ_R1_STRAIN

[workflow-ifos]
h1 =
l1 =
v1 =

[workflow-datafind]
datafind-check-frames-exist = no_test
datafind-check-segment-gaps = no_test
datafind-h1-frame-type = H1_GWOSC_O2_16KHZ_R1
datafind-l1-frame-type = L1_GWOSC_O2_16KHZ_R1
datafind-v1-frame-type = V1_GWOSC_O2_16KHZ_R1

[workflow-segments]
segments-science = +DATA,-CBC_CAT1_VETO
segments-vetoes = +CBC_CAT2_VETO,+CBC_HW_INJ,+BURST_HW_INJ

[datafind]
urltype = file
```

**Comment by ahnitz** [comment]
I had to modify the O3exp ini files to rename somethings to multiifo_statmap. Looks like just a typo.

**Comment by spxiwh** [comment]
I'm happy with this from the LIGO side. I'll wait until we can have an internal call (Friday), so that I can let the relevant people know that this is coming, and then merge.

**Pull request merged**
