### PR TITLE
self.template_id doesn't appear to be used by anything

### PR DESCRIPTION
**Pull request by tdent**

### CODE REVIEW

**Review by titodalcanton — APPROVED** [review]
Thanks for catching that @tdent. Please rebase off master to make sure the tests pass.

**Comment by tdent** [comment]
Hopefully github doesn't mind this messy looking branch update (I don't have the branch checked out remotely in a way that allows me to rebase nicely)

**Comment by titodalcanton** [comment]
Hmm this does not look right anymore! It is changing a bunch of unrelated stuff.

**Comment by titodalcanton** [comment]
Though I think I can fix this, hold on…

**Comment by tdent** [comment]
The unrelated changes should just be the more recent changes to master

**Pull request merged**
