### PR TITLE
re-enable requiring working docker builds

### PR DESCRIPTION
**Pull request by ahnitz**

### CODE REVIEW

**Comment by ahnitz** [comment]
@duncan-brown Poke

**Comment by spxiwh** [comment]
How does deleting a bunch of lines acheive this?

**Comment by ahnitz** [comment]
@spxiwh There's a section of the yml config file which just lists things to allow to fail.

**Comment by ahnitz** [comment]
@spxiwh Those items are already listed in a separate run section. The "allow_failures" one just tells travis which of the runs it does is allowed to fail.

**Comment by spxiwh** [comment]
Okay, well I've approved this, which removes the block on merging this, but I'll leave it up to you on whether to wait for @duncan-brown or not.

**Pull request merged**
