### PR TITLE
Made the pycbc_page_found_missed colourblind friendly.

### PR DESCRIPTION
**Pull request by KoustavChandra**
Made the found-missed plot colourblind friendly.

### CODE REVIEW

**Comment by KoustavChandra** [comment]
We need to update requirements.txt since it doesn't contain seaborn. In the section: # requirements for most basic library use

**Comment by GarethDaviesGW** [comment]
> We need to update requirements.txt since it doesn't contain seaborn. In the section: # requirements for most basic library use

Do you have any example outputs that we could show here?

You should be able to update requirements.txt and commit that and it should then pass Travis checks

**Comment by ahnitz** [comment]
@KoustavChandra Is there a way to do this without pulling in the seaborn dependency or does matplotlib not have any good colorblind-friendly colormaps?

**Comment by KoustavChandra** [comment]
@ahnitz I believe there is. The simplest solution as per me is not to use green and red in the same plot since the most common type of colourblindness is to separate green and red colour. So changing the colourmap to something else (from Viridis) to cividis will be enough.

**Comment by GarethDaviesGW** [comment]
cividis is based on viridis but optimised for colour deficiency and doesn't include green (which I guess was the issue with the red corsses) - maybe try that out?

**Comment by KoustavChandra** [comment]
@GarethDaviesGW you can find an example of the plot [here](https://ligo.gravity.cf.ac.uk/~koustav.chandra/LSC/images/colorblind/test.png)

**Pull request merged**
