### PR TITLE
SNR optimizer option types

### PR DESCRIPTION
**Pull request by tdent**
Fix issue in non-default settings for some options that Max complained about

### CODE REVIEW

**Review by ArthurTolley — APPROVED** [review]
Just tested this change and it fixes the previous `TypeError: can't multiply sequence by non-int of type 'float'` error. Happy to approve

**Comment by tdent** [comment]
Was that for the f-lower option?

**Comment by ArthurTolley** [comment]
@tdent I can re-run the test again to find the exact error but I simply gave `--snr-opt-extra-opts \
"--chirp-time-f-lower 20.0 --chirp-time-window 2.0 " \` and the error was there before the fix and not there after the fix :), like I said, I will re-run this in a minute.

**Comment by ArthurTolley** [comment]
This is the full error:
```
Traceback (most recent call last):
  File "/home/arthur.tolley/.conda/envs/live_rank_stat/bin/pycbc_optimize_snr", line 141, in <module>
    tau0 = cv.tau0_from_mass1_mass2(fp['mass1'][()], fp['mass2'][()], tau0flow)
  File "/home/arthur.tolley/.conda/envs/live_rank_stat/lib/python3.9/site-packages/pycbc/conversions.py", line 364, in tau0_from_mass1_mass2
    return tau0_from_mtotal_eta(mtotal, eta, f_lower)
  File "/home/arthur.tolley/.conda/envs/live_rank_stat/lib/python3.9/site-packages/pycbc/conversions.py", line 337, in tau0_from_mtotal_eta
    return _a0(f_lower) / (mtotal**(5./3.) * eta)
  File "/home/arthur.tolley/.conda/envs/live_rank_stat/lib/python3.9/site-packages/pycbc/conversions.py", line 322, in _a0
    return 5. / (256. * (numpy.pi * f_lower)**(8./3.))
TypeError: can't multiply sequence by non-int of type 'float'
```

So f_lower.

**Comment by ArthurTolley** [comment]
For the CI, maybe related to the pegasus upgrade?

Just for completeness, when applying the fix to f_lower and not chirp_time_window we get another error which is also fixed by this explicit type :) 
```
Traceback (most recent call last):
  File "/home/arthur.tolley/.conda/envs/live_rank_stat/bin/pycbc_optimize_snr", line 143, in <module>
    mintau0 = max(tau0 - args.chirp_time_window,
numpy.core._exceptions._UFuncNoLoopError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('float64'), dtype('<U3')) -> None
```

**Review by maxtrevor — CHANGES_REQUESTED** [review]
While we are improving the command line options, can we please change the verbosity option to use https://github.com/gwastro/pycbc/blob/master/pycbc/__init__.py#L69 ?

**Comment by tdent** [comment]
Max if you make a code suggestion (via the comment interface) we can accept it, although the verbose option is not related to this specific fix

**Comment by maxtrevor** [comment]
made the requested change myself, and somehow it seems to have gone through without needing to be accepted?

**Review by maxtrevor — APPROVED** [review]

**Comment by tdent** [comment]
Oh, yeah, github does let you edit someone else's PR just like that ..

**Comment by titodalcanton** [comment]
Remember to apply the right label to the PR, otherwise this risks not being deployed in the 2.1 release line.

**Pull request merged**
