### PR TITLE
simplify use of rvs

### PR DESCRIPTION
**Pull request by ahnitz**
If we have a cdfinv, then we should just use it for the rvs function rather than duplicating code. 

@cdcapano One thing I didn't touch was the qnm.py distribution however I don't understand some of the things it is doing. Why is it dealing with constraints and renormalization? The join distirbution should do both those things? What is going on there?

### CODE REVIEW

**Comment by cdcapano** [comment]
The UniformF0Tau distribution was meant for RD frequency and damping times in which you can exclude certain masses and spins (assuming Kerr), with the default excluding negative masses and naked singularities. The only way to do that is with constraints, since there's no simple analytic formula for the pdf. You could do it with the JointDistribution (and so write out the constraints in the config file), but if I remember right, this could lead to large constraint sections in the config file that were prone to typos. Hence the distribution. It's also faster this way since the constraint is hard coded rather than having to evaluate a string on each likelihood call.

**Comment by ahnitz** [comment]
@cdcapano Poke

**Review by cdcapano — COMMENTED** [review]
This looks ok, but could you double check that the CosAngle and SinAngle rvs functions still provide the right distribution of random draws when bounds are included? I think they should, but not certain looking at the cdfinv function (if not, this would be a bug in the cdfinv).

**Comment by ahnitz** [comment]
@cdcapano Looks OK to me

```
from pycbc.distributions import SinAngle, CosAngle
import numpy, pylab

x = SinAngle(x=[0, numpy.pi])
vals = x.rvs(size=100000)['x']
_ = pylab.hist(vals, bins=100)

x = CosAngle(x=[-numpy.pi/2.0, numpy.pi/2.0])
vals = x.rvs(size=100000)['x']
_ = pylab.hist(vals, bins=100)

x = SinAngle(x=[0, numpy.pi/2.0])
vals = x.rvs(size=100000)['x']
_ = pylab.hist(vals, bins=100)

x = CosAngle(x=[-numpy.pi/2.0, 0])
vals = x.rvs(size=100000)['x']
_ = pylab.hist(vals, bins=100)
```

download (87)

**Review by cdcapano — APPROVED** [review]
Ok, thanks for making those plots. Looks good.

**Pull request merged**
