### PR TITLE
Use six.with_metaclass to add metaclasses in python2 and 3

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR replaces all uses of the `__metaclass__` class variable with calls to `six.with_metaclass` to support applying metaclasses in python2 and python3 at the same time.

### CODE REVIEW

**Comment by spxiwh** [comment]
There's issues with this one ... I'm assigning to Collin without looking deeper. (Branch conflicts and CodeClimate not happy)

**Comment by duncanmmacleod** [comment]
@spxiwh, @cdcapano, I have updated this to use `six.add_metaclass` instead of `six.with_metaclass`, since `with_metaclass` confuses pylint [[ref](https://github.com/PyCQA/pylint/issues/200#issuecomment-163173718)].

**Comment by duncanmmacleod** [comment]
@cdcapano, are you able to take a look at this?

**Comment by duncanmmacleod** [comment]
@ahnitz, @spxiwh, @cdcapano, ping.

**Comment by spxiwh** [comment]
Let me give @cdcapano another day to respond to this, if he doesn't I'll just merge it. I don't really understand meta-classes, but the change looks straightforward.

**Comment by spxiwh** [comment]
No response, so merging now

**Pull request merged**
