### PR TITLE
Use HFile instead of h5py.File in most places

### PR DESCRIPTION
**Pull request by GarethCabournDavies**
Use pycbc.io.hdf's HFile class rather than h5py.File directly so that we can make changes to the functionality.

For example checksumming, version information, and anything else we may want

## Standard information about the request

This is a change to utilise potential future features
This change touches everywhere in the code, but affects nothing

This change follows style guidelines (See e.g. [PEP8](https://peps.python.org/pep-0008/)), has been proposed using the [contribution guidelines](https://github.com/gwastro/pycbc/blob/master/CONTRIBUTING.md)

## Contents
Not quite find-and-replace, but update everywhere which uses h5py.File to pycbc.io.HFile

## Links to any issues or associated PRs
#1525 #4768 

## Testing
Broadly, this should be checked by the CI running `--help` for all executables

- [x] The author of this pull request confirms they will adhere to the [code of conduct](https://github.com/gwastro/pycbc/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by GarethCabournDavies** [comment]
Note that I haven't touched `bin/plotting/pycbc_plot_bank_bins`, as that is already subclassing h5py.File, though I'm not sure whether the functionality which is there already exists elsewhere

**Comment by GarethCabournDavies** [comment]
I have also avoided live (due to efficiency worries) and inference, so as not to interfere with the h5py.File wrapper used there

**Review by spxiwh — APPROVED** [review]
I'm okay with this, any issues @ahnitz ?

**Review by ahnitz — APPROVED** [review]
Yeah, I don't have a problem with this.

**Pull request merged**
