### PR TITLE
Add support for ptemcee

### PR DESCRIPTION
**Pull request by cdcapano**
Adds support for ptemcee.

Unfortunately, the released version of ptemcee (1.0.0) is incompatible with this, as I wrote it against ptemcee's current master. Given that there's hasn't been a release of ptemcee since 2015, and the last commit to it was in 2018, I don't think it'll be updated. So, to use this, you need to install from source.

Did a quick test on the normal distribution. Putting on hold until I have a chance to test on a GW.

### CODE REVIEW

**Comment by ahnitz** [comment]
@cdcapano If there is no new release, and you have to install from master, it might be good just to make a release ourselves of ptemcee (i.e. upload to pycbc under say pycbc-ptemcee) so that there is something people can install with pip. Not needed for this patch though, just would be nice if we start using this.

**Comment by cdcapano** [comment]
@ahnitz Yeah, that's a good idea. How do you propose doing that exactly? Do you want to register a `pycbc-ptemcee` with PyPi, or just include a tar ball that can be downloaded from gwastro via pip, like we currently do with pegasus? I lean toward the latter. I don't think we want to be responsible for having to keep a registered version of ptemcee up to date.

**Comment by ahnitz** [comment]
@cdcapano The latter is probably good enough.

**Comment by ahnitz** [comment]
@cdcapano In which case you can just do it with the proper master repo of ptemcee when you add that to companion.txt.

**Comment by cdcapano** [comment]
@ahnitz I didn't realize all repos have a master tar ball. Ok, I added it to companion.txt then.

**Comment by ahnitz** [comment]
@cdcapano Some of the CC issues seem serious. This will also need to be rebased.

**Comment by cdcapano** [comment]
@ahnitz I think the complaints about ptemcee not having particular methods are because code climate isn't picking up the master version of ptemcee. In any event, I realized I forgot to add functions to read the adaptation settings from the config file, so marking back as work in progress.

**Review by ahnitz — APPROVED** [review]

**Pull request merged**
