### PR TITLE
Reset _saved in roll-function.

### PR DESCRIPTION
**Pull request by MarlinSchaefer**
Resetting the memory of the Array after the roll is applied, rather then before.

### CODE REVIEW

**Comment by ahnitz** [comment]
@MarlinSchaefer We might have made this mistake elsewhere. Do you see any other instances like this?

**Comment by ahnitz** [comment]
@MarlinSchaefer Travis errors don't appear related to your patch, but instead it looks like some LIGO links are down.

**Comment by MarlinSchaefer** [comment]
@ahnitz Can/Should we just restart the Travis runs in that case?

**Comment by ahnitz** [comment]
@MarlinSchaefer Please rebase your branch from the current master. It should pass travis then.

**Pull request merged**
