### PR TITLE
Avoid pegasus 5.0.7

### PR DESCRIPTION
**Pull request by spxiwh**
This version has a bug we don't want. The 5.0.8 release should be fine. Did I miss any file?

### CODE REVIEW

**Comment by ahnitz** [comment]
@spxiwh I think we need to have the pegasus binaries also be version constrained e.g. the ones installed for the workflow tests. I don't recall how the lvk images are done, so might be worth checking if that is already pinned.

**Comment by ahnitz** [comment]
@spxiwh Unless of course, the bug doesn't appear if you just use the old api version, but the newer planner version. I didn't test that myself. Does that work?

**Comment by spxiwh** [comment]
This is something in the planner, so yeah, pinning the API isn't doing anything ....

**Comment by spxiwh** [comment]
@ahnitz This fixes the CI ... It should be reverted once the pegasus 5.0.8 release is made. I've asked LVK clusters not to upgrade to the 5.0.7 executables. Others using PyCBC+pegasus should also stick at 5.0.6 until a new release is available.

**Review by ahnitz — APPROVED** [review]

**Pull request merged**
