### PR TITLE
multi-ifo changes to pycbc_page_segtable

### PR DESCRIPTION
**Pull request by GarethDaviesGW**
Making it so that H1 & L1 are not longer hardcoded, and that the table output now has all possible detector combinations

### CODE REVIEW

**Comment by tdent** [comment]
Can you post links to some tests Gareth?

**Comment by GarethDaviesGW** [comment]
Segtable with 3 IFOs and multiple rows to check:

https://ldas-jobs.ligo.caltech.edu/~gdavies/testoutput/test_segtable_output.html

I'm not sure how this will look on the actual results page though, as it is now a much wider table

**Comment by tdent** [comment]
@spxiwh OK on the output from my point of view, however the functions to iterate over ifo combinations (`ifo_combinations` and `powerset_ifos`) seem like they might be more generally useful or maybe already exist somewhere - we're guessing you may know more about this

**Comment by tdent** [comment]
@spxiwh can you look at this/review briefly? the one issue I had is whether the powerset_ifos function either exists elsewhere already or belongs in a library module, eg in the workflow module ?

**Comment by GarethDaviesGW** [comment]
looking at https://ldas-jobs.ligo.caltech.edu/~gdavies/testoutput/H1L1-PAGE_SEGTABLE_VETO_SUMMARY-1187312718-428100.html in #2509 has made me want to have a look at this again at some point, need to understand if this is doing this right

I'm not sure if V1 segments are in a dfferent format and therefore need special treatment

**Pull request merged**
