### PR TITLE
add PASTRO_READY label

### PR DESCRIPTION
**Pull request by tdent**
Addressing requests from Low Latency chairs

### CODE REVIEW

**Comment by titodalcanton** [comment]
@tdent do you know if this has a specific requirement in terms of ligo-gracedb version?

**Comment by tdent** [comment]
> @tdent do you know if this has a specific requirement in terms of ligo-gracedb version?

Yes, this is a recent addition to the gracedb interface (https://git.ligo.org/computing/sccb/-/issues/1085) which is now running in playground, do we need to note this somewhere?

**Comment by titodalcanton** [comment]
Yes, please edit `companion.txt` to require ligo-gracedb 2.10.0.

I should make sure that the various environments are up to date with it.

**Comment by titodalcanton** [comment]
I am also thinking that applying the label should come *before* making and uploading the plots, which is just for humans and can take its time. That involves rearranging some code though, so maybe we want to keep that a separate PR.

**Comment by tdent** [comment]
I don't think we make a specific multi-pastro plot, so I guess this is mainly concerned with SNR and PSD plots .. so yes, in general sending tiny .json files should take precedence over doing things with matplotlib. Material for another issue.

**Review by titodalcanton — APPROVED** [review]

**Pull request merged**
