### PR TITLE
allow graceful exit

### PR DESCRIPTION
**Pull request by ahnitz**
I think this may be what is needed to shut down the mpi pool more gracefully.

### CODE REVIEW

**Comment by ahnitz** [comment]
Assigning to @spxiwh since @cdcapano is on vacation. The issue was affecting Ian anyway, so at the very least we may get confirmation if this resolves the issue.

**Comment by spxiwh** [comment]
I'll add this onto my branch now, but it may take a while to finish an end-to-end test of this. Maybe there is no rush for this at the moment though

**Comment by spxiwh** [comment]
I haven't had a successful job since adding this patch to my branch ... sorry

**Comment by spxiwh** [comment]
I'm going to merge this, and we can revisit if there are problems (can someone get this onto GWIN as well, if needed).

**Pull request merged**
