### PR TITLE
Added remnant threshold mass to pycbc_brute_bank

### PR DESCRIPTION
**Pull request by MarcoCusinato**
Features added:
- Maximum mass sustained by a Neutron star
- EOS selection
- Possibility to discriminate NS-BH events with a remnant disk mass below a certain threshold (using foucart18 in pycbc/pycbc/neutron_stars/eos_util.py)
- replaced `for` cycles with Python list and dictionary comprehensions (a bit faster)

Two images showing what the threshold does are attached.
The first one is a "plain" bank generation with the following parameters
```
--minimal-match 0.97 \
--tolerance .005 \
--buffer-length 2 \
--sample-rate 2048 \
--tau0-threshold 0.5 \
--approximant IMRPhenomD \
--tau0-crawl 5 \
--tau0-start 0 \
--tau0-end 600 \
--psd-file /home/marco.cusinato/banks/brute_banks/O3a/H1L1-AVERAGE_PSD-1239184818-128800.txt \
--min 1 1 0. 0. \
--max 25 2.8346480922 .998 .05 \
--params mass1 mass2 spin1z spin2z \
--seed 1915 \
--low-frequency-cutoff 27.0
```
In the second one, we consider only BNS events and NS-BH with a remnant mass strictly greater than 0
```
--minimal-match 0.97 \
--tolerance .005 \
--buffer-length 2 \
--sample-rate 2048 \
--tau0-threshold 0.5 \
--approximant IMRPhenomD \
--tau0-crawl 5 \
--tau0-start 0 \
--tau0-end 600 \
--psd-file /home/marco.cusinato/banks/brute_banks/O3a/H1L1-AVERAGE_PSD-1239184818-128800.txt \
--min 1 1 0. 0. \
--max 25 2.8346480922 .998 .05 \
--params mass1 mass2 spin1z spin2z \
--seed 1915 \
--low-frequency-cutoff 27.0\
--remnant-mass-threshold 0.0
```

no_threshold
threshold

### CODE REVIEW

**Comment by ahnitz** [comment]
@MarcoCusinato Apologies, I missed your PR earlier. I wanted to ask though, is this something that you actually need to modify the script for? We support choosing the parameterization (including constraints, etc) using the config file syntax. Does that serve the needs here? The options for things like max mass / max-q are somewhat holdovers from when the parameters were put in manually, but I think the config format is much more flexible. If that doesn't suit your needs, perhaps we should think about how to allow it to do so? What do you think? 

Also, if we don't reply soon enough, please feel free to poke us in the gwastro slack workspace. We welcome your ideas there. Let me know if you aren't already a member. A number of University members and ligo.org emails can automatically join, others one of us has to invite manually.

**Comment by WuShichao** [comment]
@MarcoCusinato As Alex said, the bank script supports the .ini file (using `--input-config`), which contains the prior and all constraints. Please let us know if it works.

**Comment by pannarale** [comment]
To follow your suggestion, we opened a new PR #4299

**Comment by pannarale** [comment]
Closing: superseded by PR https://github.com/gwastro/pycbc/pull/4299.

**Pull request closed without merging**
