### PR TITLE
correlate unittest was was broken for the Correlator class

### PR DESCRIPTION
**Pull request by ahnitz**

### CODE REVIEW

**Comment by ahnitz** [comment]
This test should have caught the bug in the correlation class but was not in fact testing correctly for the class version.

**Comment by tdent** [comment]
I don't think I know how to review this. Who else is actively involved in this code (eg Josh, Ian)? 

Only thing I can suggest is to update/correct the comment at the top saying "These are the unittests for the pycbc.waveform module"

**Comment by spxiwh** [comment]
It looks like the correlator is fully overwriting z anyway, so how does initializing this to 0 instead of 1 help?

**Comment by ahnitz** [comment]
@spxiwh The bug was that the output vector was being copied from the *expected* output. The correlate function was broken for the class interface so it wasn't overwriting the output, but the test passed since it already contained what I expected to find. Now it contains zeros, and will fail unless the correlate function actually fills it with the correct values.

**Pull request merged**
