### PR TITLE
Make combine statmap options more like actual usage

### PR DESCRIPTION
**Pull request by tdent**
Previous default behaviour (before #4053) was to remove against inclusive FAR at the combine statmap stage, so add this option in order to test HR in this stage going forwards

### CODE REVIEW

**Comment by GarethCabournDavies** [comment]
That looks sensible to me

**Comment by tdent** [comment]
@ahnitz any idea how to diagnose the small workflow failures?

**Comment by tdent** [comment]
> I had a quick look in the logs, and it is failing on the add_statmap injection jobs, which makes sense as the injection files dont have inclusive ifars.
> 
That makes sense .. but where do you find the logs?

**Comment by GarethCabournDavies** [comment]
> > I had a quick look in the logs, and it is failing on the add_statmap injection jobs, which makes sense as the injection files dont have inclusive ifars.
> 
> That makes sense .. but where do you find the logs?

Click details next to the failed jobs, then under "summary" on the left hand side, it has the logs under artifacts
image

**Comment by tdent** [comment]
> > > I had a quick look in the logs, and it is failing on the add_statmap injection jobs, which makes sense as the injection files dont have inclusive ifars.
> >  
> > That makes sense .. but where do you find the logs?
> 
> Click details next to the failed jobs, then under "summary" on the left hand side, it has the logs under artifacts 

Oh, I was looking in the 'build' section which has a bit at the end about 'storing log files', however that in the end turned out to only be the dagman log file for running the workflow, not the individual job logs.  As those are 160MB I'm impressed that you managed to look quickly.

**Comment by tdent** [comment]
Well, still failing ..

**Comment by tdent** [comment]
The error was in a foreground minifollowup job .. 
```
Traceback (most recent call last):
          File "/opt/hostedtoolcache/Python/3.8.13/x64/bin/pycbc_foreground_minifollowup", line 107, in <module>
            raise KeyError('Sort variable {0} not in {1}: sort choices in '
        KeyError: 'Sort variable ifar not in background_exc: sort choices in background_exc are H1/time, H1/trigger_id, L1/time, L1/trigger_id, V1/time, V1/trigger_id, decimation_factor, stat, template_id, timeslide_id'
```

**Comment by tdent** [comment]
OK, I think I know what is happening here .. production plotting ini files say to sort on 'stat' not ifar, and ifar doesn't exist for time slide events.

**Pull request merged**
