### PR TITLE
Add numerical phase marginalization for HM waveforms

### PR DESCRIPTION
**Pull request by cdcapano**
Adds a generator and model for numerical phase marginalization. Currently only works with `NRSur7dq4`. Has functions for IMRPhenomPv3HM and PhenomXPHM, but these currently don't work for precessing waveforms, due to issues with frame conventions in lalsimulation.

### CODE REVIEW

**Comment by cdcapano** [comment]
Ok, this is about as ready as it can be. It at least works for the NR Surrogate models. I've removed support for the PhenomP* waveforms, as it's too difficult to get the modes separately from them. I've left in the function to get the PhenomXPHM modes, but have disabled it for now. The problem with that waveform is it adds the +/-m modes together automatically. I think they are working on fixing this in `lalsimulation` (is that right @Cyberface?), so it should be straight forward to add back support once that's changed. If not, it still might be possible to separate the +/-m modes for the waveform.

Anyway, summary of changes:
 * I've added `waveform_modes.py` module to the `waveform` package. This has functions to generate FD and TD waveforms mode-by-mode, without applying spherical harmonics. The convention I've used is that these functions return the real and imaginary parts of the complex hlm time series as a tuple. For the FD version, it will return the equivalent of the FFT of the real and imaginary parts of the complex hlm time series. That way we do not need to worry about handling complex -> complex FFTs.
 * I've added a couple of generators and a new detector frame generator to call the waveform mode functions.
 * We've (myself + @ahnitz) have added a model to numerically marginalize over both the phase and polarization using the mode-by-mode waveform generator. This could also be generalized to work with single-mode waveforms, but I leave that for a future PR.

**Comment by cdcapano** [comment]
Making @spxiwh reviewer since @ahnitz contributed to this.

**Comment by spxiwh** [comment]
I think if you want me to review this, it would be good to break this down a little bit. Can we have this split into:

 * New utility functions that add clear input/outputs (grouped together as is logical) and would not touch existing code
 * Changes in generator.py to add the new mode-content generation. This does seem to touch existing code, so we'd want to be easily see that this won't break anything.
 * Changes in the inference code to add the functionality to use the above.

At the moment there's just a bit too much to check over in one block!

**Comment by cdcapano** [comment]
@spxiwh Sorry about that. I've separated this into three separate PRs: #3482, #3483, and #3484 (note that those are cumulative; I'll rebase them as they are approved). Closing this in favor of them.

**Pull request closed without merging**
