### PR TITLE
patch to hack macs to work

### PR DESCRIPTION
**Pull request by ahnitz**
Attempt to add in fix recommend in #3054

### CODE REVIEW

**Comment by titodalcanton** [comment]
I tested this change on an anaconda env, and at least it does not appear to break the install. I did not do extensive tests though.

**Comment by ahnitz** [comment]
@titodalcanton @spxiwh Would either of you be happy to approve this? It seems @titodalcanton was able to verify this didn't break building on a mac and it would seem to resolve some mac circumstances. I can't really test further than that, unfortunately.

**Review by spxiwh — APPROVED** [review]
I'll approve this ... I think the problems reported were on up-to-date mac OS versions, which I don't have, but I don't see any harm in this.

**Comment by titodalcanton** [comment]
My tests were on macOS 10.15.6 (up to date). No issues with merging this.

**Pull request merged**
