### PR TITLE
Results page generation command

### PR DESCRIPTION
**Pull request by GarethCabournDavies**
Add the command used to generate the workflow to its own page (rather than remaining in the metadata of other files only)

### CODE REVIEW

**Comment by ahnitz** [comment]
@GarethCabournDavies You should see the 'results' zip file here 

https://github.com/gwastro/pycbc/actions/runs/3516714213

That should contain the web page so you can just download/extract that and view offline to see if it worked as you wanted.

**Comment by GarethCabournDavies** [comment]
Thanks! I managed to get them displaying and it looked a bit off, so it now looks a bit better

**Comment by GarethCabournDavies** [comment]
This resolves #3526

**Comment by GarethCabournDavies** [comment]
Example of the updated output:
image

**Comment by ahnitz** [comment]
@GarethCabournDavies Should this be a section in the "well" i.e. at the top and always visible or in the B section where it would be shaded by default? The latter you can do by just not including the file in any layout well file.

**Comment by GarethCabournDavies** [comment]
I think it makes sense in the well - the log is straight after it, so to me it makes sense for the workflow section to show Command then Log for the workflow generation

**Comment by GarethCabournDavies** [comment]
I'm going to be away now until the new year, but I am happy for edits to be made and this to be merged when ready

**Review by ahnitz — APPROVED** [review]

**Pull request merged**
