### PR TITLE
turn on testing with python 3.11

### PR DESCRIPTION
**Pull request by ahnitz**

### CODE REVIEW

**Comment by ahnitz** [comment]
Ok, I think the first set of errors was due to h5py not being released yet. I just checked and there was an update to h5py 2 hours ago that should hopefully resolve that issue. We'll see if anything else pops up.

**Comment by ahnitz** [comment]
Ok, h5py is ok now. Now the blocker is awkde

```Stored in directory: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-ephem-wheel-cache-bp0oawiu/wheels/73/cc/89/b3e40518485fc6c713d8f6a6c31ef3d25d7b4530fd4c8e8e7e
  Building wheel for awkde (pyproject.toml): started
  Building wheel for awkde (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for awkde (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [75 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-cpython-311
      creating build/lib.macosx-10.9-x86_64-cpython-311/awkde
      copying awkde/tools.py -> build/lib.macosx-10.9-x86_64-cpython-311/awkde
      copying awkde/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-311/awkde
      copying awkde/awkde.py -> build/lib.macosx-10.9-x86_64-cpython-311/awkde
      running build_ext
      clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/runner/work/pycbc/pycbc/.tox/py-unittest/include -fPIC -O2 -isystem /Users/runner/work/pycbc/pycbc/.tox/py-unittest/include -I/Users/runner/work/pycbc/pycbc/.tox/py-unittest/include/python3.11 -c flagcheck.cpp -o flagcheck.o -std=c++17
      building 'awkde.backend' extension
      creating build/temp.macosx-10.9-x86_64-cpython-311
      creating build/temp.macosx-10.9-x86_64-cpython-311/cpp
      clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/runner/work/pycbc/pycbc/.tox/py-unittest/include -fPIC -O2 -isystem /Users/runner/work/pycbc/pycbc/.tox/py-unittest/include -I/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-u8_okncf/overlay/lib/python3.11/site-packages/pybind11/include -I/Users/runner/work/pycbc/pycbc/.tox/py-unittest/include/python3.11 -c cpp/backend.cpp -o build/temp.macosx-10.9-x86_64-cpython-311/cpp/backend.o -std=c++17 -mmacosx-version-min=10.14 -fvisibility=hidden -g0 -stdlib=libc++ -O3
      In file included from cpp/backend.cpp:1:
      In file included from /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-u8_okncf/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:45:
      In file included from /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-u8_okncf/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/attr.h:13:
      /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-u8_okncf/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/cast.h:446:36: error: member access into incomplete type 'PyFrameObject' (aka '_frame')
                      "  " + handle(frame->f_code->co_filename).cast<std::string>() +
                                         ^
      /Users/runner/work/pycbc/pycbc/.tox/py-unittest/include/python3.11/pytypedefs.h:22:16: note: forward declaration of '_frame'
      typedef struct _frame PyFrameObject;
                     ^
      In file included from cpp/backend.cpp:1:
      In file included from /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-u8_okncf/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:45:
      In file included from /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-u8_okncf/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/attr.h:13:
      /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-u8_okncf/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/cast.h:448:29: error: member access into incomplete type 'PyFrameObject' (aka '_frame')
                      handle(frame->f_code->co_name).cast<std::string>() + "\n";
                                  ^
      /Users/runner/work/pycbc/pycbc/.tox/py-unittest/include/python3.11/pytypedefs.h:22:16: note: forward declaration of '_frame'
      typedef struct _frame PyFrameObject;
                     ^
      In file included from cpp/backend.cpp:1:
      In file included from /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-u8_okncf/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:45:
      In file included from /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-u8_okncf/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/attr.h:13:
      /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-u8_okncf/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/cast.h:449:26: error: member access into incomplete type 'PyFrameObject' (aka '_frame')
                  frame = frame->f_back;
                               ^
      /Users/runner/work/pycbc/pycbc/.tox/py-unittest/include/python3.11/pytypedefs.h:22:16: note: forward declaration of '_frame'
      typedef struct _frame PyFrameObject;
                     ^
      In file included from cpp/backend.cpp:1:
      /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-u8_okncf/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:2291:49: error: no member named 'frame' in '_ts'
          PyFrameObject *frame = PyThreadState_Get()->frame;
                                 ~~~~~~~~~~~~~~~~~~~  ^
      /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-u8_okncf/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:2292:41: error: member access into incomplete type 'PyFrameObject' (aka '_frame')
          if (frame && (std::string) str(frame->f_code->co_name) == name &&
                                              ^
      /Users/runner/work/pycbc/pycbc/.tox/py-unittest/include/python3.11/pytypedefs.h:22:16: note: forward declaration of '_frame'
      typedef struct _frame PyFrameObject;
                     ^
      In file included from cpp/backend.cpp:1:
      /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-u8_okncf/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:2293:14: error: member access into incomplete type 'PyFrameObject' (aka '_frame')
              frame->f_code->co_argcount > 0) {
                   ^
      /Users/runner/work/pycbc/pycbc/.tox/py-unittest/include/python3.11/pytypedefs.h:22:16: note: forward declaration of '_frame'
      typedef struct _frame PyFrameObject;
                     ^
      In file included from cpp/backend.cpp:1:
      /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-u8_okncf/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:2296:18: error: member access into incomplete type 'PyFrameObject' (aka '_frame')
                  frame->f_locals, PyTuple_GET_ITEM(frame->f_code->co_varnames, 0));
                       ^
      /Users/runner/work/pycbc/pycbc/.tox/py-unittest/include/python3.11/pytypedefs.h:22:16: note: forward declaration of '_frame'
      typedef struct _frame PyFrameObject;
                     ^
      In file included from cpp/backend.cpp:1:
      /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-u8_okncf/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:2296:52: error: member access into incomplete type 'PyFrameObject' (aka '_frame')
                  frame->f_locals, PyTuple_GET_ITEM(frame->f_code->co_varnames, 0));
                                                         ^
      /Users/runner/work/pycbc/pycbc/.tox/py-unittest/include/python3.11/pytypedefs.h:22:16: note: forward declaration of '_frame'
      typedef struct _frame PyFrameObject;
                     ^
      8 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for awkde
  Building wheel for astroplan (pyproject.toml): started
  Building wheel for astroplan (pyproject.toml): finished with status 'done'
  Created wheel for astroplan: filename=astroplan-0.8-py3-none-any.whl size=83258 sha256=18e65f57393ef6f5eca17b4b8c891313116311ca50eca03b1b474b6bce2a2481
  Stored in directory: /Users/runner/Library/Caches/pip/wheels/d9/16/dc/3894816be[201](https://github.com/gwastro/pycbc/actions/runs/3960272551/jobs/6834867228#step:5:202)360357a2dff63ced5f45c548d79b9cb4a1492c
  Building wheel for future (setup.py): started
  Building wheel for future (setup.py): finished with status 'done'
  Created wheel for future: filename=future-0.18.3-py3-none-any.whl size=49[202](https://github.com/gwastro/pycbc/actions/runs/3960272551/jobs/6834867228#step:5:203)5 sha256=87e70fdbb7b3dcde0c1ae5fbfa1138b620a849f0[213](https://github.com/gwastro/pycbc/actions/runs/3960272551/jobs/6834867228#step:5:214)ccb739c107[217](https://github.com/gwastro/pycbc/actions/runs/3960272551/jobs/6834867228#step:5:218)de11bc6d
  Stored in directory: /Users/runner/Library/Caches/pip/wheels/83/31/5a/7539ed9c6ac3[249](https://github.com/gwastro/pycbc/actions/runs/3960272551/jobs/6834867228#step:5:250)781de831638629a4fe503168023e1a777e2
Successfully built ligo-gracedb cpnest ultranest ptemcee astroplan future
Failed to build awkde
ERROR: Could not build wheels for awkde, which is required to install pyproject.toml-based projects

=================================== log end ====================================
ERROR: could not install deps [:preinstall:-rrequirements.txt, -rcompanion.txt, mkl;'arm' not in platform_machine, pytest]; v = InvocationError('/Users/runner/work/pycbc/pycbc/.tox/py-unittest/bin/python -m pip install -rcompanion.txt \'mkl;\'"\'"\'arm\'"\'"\' not in platform_machine\' pytest', 1)
___________________________________ summary ____________________________________
ERROR:   py-unittest: could not install deps [:preinstall:-rrequirements.txt, -rcompanion.txt, mkl;'arm' not in platform_machine, pytest]; v = InvocationError('/Users/runner/work/pycbc/pycbc/.tox/py-unittest/bin/python -m pip install -rcompanion.txt \'mkl;\'"\'"\'arm\'"\'"\' not in platform_machine\' pytest', 1)
Error: Process completed with exit code 1.
```

**Comment by titodalcanton** [comment]
I played a bit with the awkde issue and maybe fixed it: https://github.com/mennthor/awkde/pull/10.

**Comment by titodalcanton** [comment]
@ahnitz I pointed `companion.txt` to my awkde fork to see if we spot anything else while the awkde fix goes upstream. We should also rebase on master to pick the ligo-gracedb version change, I did not want to rebase somebody else's branch.

**Comment by ahnitz** [comment]
@titodalcanton Thanks for addressing that! I'll rebase the branch. It looks like everything passes with your awkde fix. Is this something we should wait for an upstream release for or go ahead with your patched version until that is out?

**Comment by ahnitz** [comment]
@titodalcanton @spxiwh My opinion is we should just merge and then revert the one line once awkde gets a release. We don't know the timescale for changes on their end and in the meantime, it is better to have a more complete test suite going. People are actively using python3.11, so I'd prefer not to get too caught out.

**Comment by spxiwh** [comment]
I'll let Tito approve, but I'm happy with this!

**Review by titodalcanton — APPROVED** [review]

**Pull request merged**
